import type { Metadata } from "next";
import LegalPage from "@/components/legal-page";

export const metadata: Metadata = { title: "Política de cookies", description: "Información sobre las cookies y tecnologías similares utilizadas por CoinRenta." };
const P = ({ children }: { children: React.ReactNode }) => <p>{children}</p>;

export default function CookiesPage() {
  return <LegalPage label="Cookies y tecnologías similares" title="Política de cookies" intro="Te explicamos qué cookies y tecnologías similares utiliza CoinRenta, para qué sirven, cuáles requieren consentimiento y cómo puedes modificar o retirar tus preferencias." updated="14 de septiembre de 2026" activePath="/legal/cookies" sections={[
    { title: "1. Qué son las cookies", children: <P>Las cookies y tecnologías similares son pequeños identificadores que pueden almacenarse o acceder al dispositivo para permitir funciones técnicas, recordar preferencias o medir el uso de un servicio. Pueden implicar tratamiento de datos personales dependiendo de la configuración y finalidad.</P> },
    { title: "2. Cookies y tecnologías estrictamente necesarias", children: <><P>CoinRenta utiliza tecnologías estrictamente necesarias para autenticación, mantenimiento de sesión, seguridad y funcionamiento esencial del servicio. Cuando una tecnología es necesaria para prestar el servicio solicitado o para una finalidad exclusivamente técnica comprendida en las excepciones legales, no se requiere consentimiento previo.</P><div className="legal-table-wrap"><table className="legal-table"><thead><tr><th>Finalidad</th><th>Proveedor / tecnología</th><th>Consentimiento</th></tr></thead><tbody><tr><td>Autenticación y sesión</td><td>CoinRenta / Supabase Auth</td><td>No, cuando sea estrictamente necesaria</td></tr><tr><td>Seguridad y prevención de abusos</td><td>CoinRenta / infraestructura</td><td>No, cuando sea estrictamente necesaria</td></tr><tr><td>Pago y proceso de checkout</td><td>Stripe, cuando se utilice para contratar Premium</td><td>Según las cookies/técnicas concretas utilizadas en el proceso de pago</td></tr></tbody></table></div></> },
    { title: "3. Google Analytics", children: <P>CoinRenta podrá utilizar Google Analytics para obtener estadísticas sobre visitas y uso del sitio. Estas tecnologías se consideran no necesarias para la prestación básica de la web y, por ello, <strong>no se cargarán antes de que el usuario haya prestado su consentimiento</strong>. Si no se concede el consentimiento, Google Analytics permanecerá desactivado.</P> },
    { title: "4. Cómo se solicita el consentimiento", children: <P>Cuando existan cookies o tecnologías que requieran consentimiento, el aviso mostrará de forma clara las opciones de <strong>Aceptar</strong>, <strong>Rechazar</strong> y <strong>Configurar</strong>, con las opciones de aceptar y rechazar al mismo nivel y con visibilidad equivalente. El consentimiento se obtendrá mediante una acción afirmativa clara; la mera navegación o inacción no se utilizará como consentimiento.</P> },
    { title: "5. Configuración por categorías", children: <><P>Las preferencias se gestionan por categorías. Las tecnologías estrictamente necesarias permanecen activas porque son necesarias para el servicio. Las tecnologías analíticas podrán activarse o mantenerse desactivadas según la elección del usuario.</P><P>La elección podrá modificarse posteriormente mediante el control <strong>“Privacidad · Cookies”</strong> disponible en el sitio.</P></> },
    { title: "6. Retirada y conservación de la decisión", children: <P>Puedes retirar o modificar tu consentimiento en cualquier momento con la misma facilidad con la que lo otorgaste. CoinRenta conservará la decisión durante un periodo limitado y la volverá a solicitar cuando sea necesario por cambios relevantes o expiración de la elección. Como práctica de privacidad, se utiliza actualmente un periodo máximo de 180 días para esta preferencia.</P> },
    { title: "7. Google y posibles transferencias internacionales", children: <P>Google y sus proveedores pueden tratar información desde ubicaciones situadas fuera del Espacio Económico Europeo. Cuando el tratamiento requiera una transferencia internacional de datos personales, se utilizarán los mecanismos jurídicos y garantías previstos en el RGPD. Consulta la Política de privacidad para más información.</P> },
    { title: "8. Stripe y pagos", children: <P>Cuando CoinRenta implemente la contratación de Premium mediante Stripe, el proceso de pago podrá implicar tecnologías técnicas propias de Stripe necesarias para autenticar la sesión de pago, prevenir fraude o completar la transacción. También podrán existir tecnologías adicionales de Stripe que dependan de la configuración concreta del checkout. La relación contractual y el tratamiento de datos del pago estarán sujetos, además, a la información y políticas de Stripe que correspondan.</P> },
    { title: "9. Navegadores", children: <P>El usuario puede configurar su navegador para bloquear o eliminar cookies. El bloqueo de cookies estrictamente necesarias puede impedir el inicio de sesión o el funcionamiento de determinadas funciones.</P> },
    { title: "10. Más información", children: <P>Para conocer el tratamiento de datos personales, consulta la <a href="/legal/privacidad">Política de privacidad</a>. Para cualquier consulta sobre cookies y privacidad: <strong>info@coinrenta.es</strong>.</P> },
    { title: "11. Actualizaciones", children: <P>Esta política podrá actualizarse cuando cambien las tecnologías utilizadas, los proveedores, el modelo de negocio o la normativa aplicable. La versión publicada en esta página será la vigente.</P> },
  ]} />;
}
