import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import type { ReactNode } from "react";
import { createClient } from "@/lib/supabase/server";
import { updateProfile } from "../actions";
import ExchangeManager from "../exchange-manager";

const sections: Record<string,{title:string;description:string}>={exchanges:{title:"Exchanges",description:"Gestiona tus conexiones y sincroniza tus datos."},movimientos:{title:"Movimientos",description:"Consulta los movimientos normalizados de tus cuentas."},fiscalidad:{title:"Fiscalidad",description:"Revisa ejercicios, lotes fiscales y resultados."},configuracion:{title:"Configuración",description:"Gestiona tu perfil y preferencias."}};
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{section:string}>}):Promise<Metadata>{const {section}=await params;if(!sections[section])return{title:"No encontrado",robots:{index:false,follow:false}};return{title:sections[section].title,description:sections[section].description,robots:{index:false,follow:false}};}
function date(value:string|null){return value?new Intl.DateTimeFormat("es-ES",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";}

export default async function DashboardSection({params}:{params:Promise<{section:string}>}){const {section}=await params;const item=sections[section];if(!item)notFound();const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 if(section==="exchanges"){
  const [{data:exchanges},{data:connections}]=await Promise.all([supabase.from("exchanges").select("id,code,name,website").eq("is_active",true).order("name"),supabase.from("exchange_connections").select("id,exchange_id,label,status,last_sync_at,last_sync_status,last_sync_error,api_secret_id,provider_type,exchanges(name,code)").eq("user_id",user.id).order("created_at",{ascending:false})]);
  return <Page title={item.title} description={item.description} active={section}>
    <div className="exchange-hero panel-card">
      <div className="exchange-hero-copy"><span className="section-kicker">Conexiones</span><h3>Gestiona tus exchanges</h3><p>Añade una conexión o vuelve a sincronizar todos tus datos desde las APIs conectadas.</p></div>
      <ExchangeManager exchanges={exchanges||[]} />
    </div>
    <div className="panel-card">
      <div className="panel-head"><div><span className="section-kicker">Tus conexiones</span><h3>{connections?.length??0} conexiones</h3></div></div>
      {connections?.length?<div className="data-list">{connections.map(c=>{const ex=Array.isArray(c.exchanges)?c.exchanges[0]:c.exchanges;return <div className="data-row" key={c.id}><div><strong>{ex?.name||"Exchange"}</strong><span>{c.label||"Sin nombre"} · {c.provider_type==="csv"?"CSV":"API"}</span></div><span className={`status-pill ${c.status==="active"||c.last_sync_status==="success"?"status-success":""}`}>{c.status}</span><span>{date(c.last_sync_at)}</span></div>})}</div>:<Empty text="Todavía no tienes exchanges conectados."/>}
    </div>
    <div className="panel-card">
      <div className="panel-head"><div><span className="section-kicker">Cómo funciona</span><h3>Una sola pantalla para tus conexiones</h3></div></div>
      <div className="info-grid"><div><strong>API</strong><span>Conecta un exchange mediante una clave de solo lectura y sincroniza sus movimientos automáticamente.</span></div><div><strong>CSV</strong><span>Si prefieres importar un histórico, puedes hacerlo al crear una nueva conexión.</span></div><div><strong>Resincronizar</strong><span>Elimina los movimientos descargados y vuelve a obtenerlos desde las conexiones API.</span></div></div>
    </div>
  </Page>;
 }
 if(section==="movimientos"){const {data:transactions}=await supabase.from("transactions").select("id,occurred_at,transaction_type,base_amount,quote_amount,price_currency,source,external_id,accounts(name)").eq("user_id",user.id).order("occurred_at",{ascending:false}).limit(100);return <Page title={item.title} description={item.description} active={section}><div className="panel-card"><div className="panel-head"><div><span className="section-kicker">Últimos movimientos</span><h3>{transactions?.length??0} registros mostrados</h3></div></div>{transactions?.length?<div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Cuenta</th><th>Base</th><th>Quote</th><th>Origen</th></tr></thead><tbody>{transactions.map(tx=><tr key={tx.id}><td>{date(tx.occurred_at)}</td><td>{tx.transaction_type}</td><td>{(tx.accounts as {name?:string}|null)?.name||"—"}</td><td>{tx.base_amount??"—"}</td><td>{tx.quote_amount??"—"} {tx.price_currency||""}</td><td>{tx.source}</td></tr>)}</tbody></table></div>:<Empty text="Todavía no hay movimientos. Conecta un exchange o importa un histórico."/>}</div></Page>}
 if(section==="fiscalidad"){const [{data:years},{data:disposals}]=await Promise.all([supabase.from("tax_years").select("id,year,status,created_at,updated_at").eq("user_id",user.id).order("year",{ascending:false}),supabase.from("tax_disposals").select("id,tax_year_id,quantity,proceeds_eur,cost_basis_eur,gain_loss_eur,assets(symbol)").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100)]);const gain=(disposals||[]).reduce((s,r)=>s+Number(r.gain_loss_eur||0),0);return <Page title={item.title} description={item.description} active={section}><div className="stat-grid"><article className="stat-card"><span className="stat-label">Ejercicios</span><strong>{years?.length??0}</strong><span className="stat-note">Configurados</span></article><article className="stat-card stat-card-accent"><span className="stat-label">Resultado registrado</span><strong>{gain.toLocaleString("es-ES",{minimumFractionDigits:2})} €</strong><span className="stat-note">Ganancias/pérdidas</span></article></div><div className="panel-card"><div className="panel-head"><div><span className="section-kicker">Ejercicios</span><h3>Histórico fiscal</h3></div></div>{years?.length?<div className="data-list">{years.map(y=><div className="data-row" key={y.id}><div><strong>Ejercicio {y.year}</strong><span>{date(y.updated_at)}</span></div><span className="status-pill">{y.status}</span></div>)}</div>:<Empty text="Todavía no hay ejercicios fiscales creados."/>}</div><div className="panel-card"><div className="panel-head"><div><span className="section-kicker">Disposiciones</span><h3>Resultados calculados</h3></div></div>{disposals?.length?<div className="table-wrap"><table><thead><tr><th>Activo</th><th>Cantidad</th><th>Venta EUR</th><th>Coste EUR</th><th>Resultado</th></tr></thead><tbody>{disposals.map(r=><tr key={r.id}><td>{(r.assets as {symbol?:string}|null)?.symbol||"—"}</td><td>{r.quantity}</td><td>{Number(r.proceeds_eur).toLocaleString("es-ES",{minimumFractionDigits:2})}</td><td>{Number(r.cost_basis_eur).toLocaleString("es-ES",{minimumFractionDigits:2})}</td><td>{Number(r.gain_loss_eur).toLocaleString("es-ES",{minimumFractionDigits:2})} €</td></tr>)}</tbody></table></div>:<Empty text="Todavía no hay disposiciones calculadas."/>}</div></Page>}
 const {data:profile}=await supabase.from("profiles").select("display_name,country_code,timezone").eq("id",user.id).maybeSingle();return <Page title={item.title} description={item.description} active={section}><div className="panel-card"><div className="panel-head"><div><span className="section-kicker">Perfil</span><h3>Datos de tu cuenta</h3></div></div><form action={updateProfile} className="form-grid"><label>Nombre visible<input name="display_name" defaultValue={profile?.display_name||""} placeholder="Tu nombre"/></label><label>País<input value={profile?.country_code||"ES"} readOnly/></label><label>Zona horaria<input value={profile?.timezone||"Europe/Madrid"} readOnly/></label><div><button className="btn btn-primary" type="submit">Guardar cambios</button></div></form></div></Page>;
}

function Page({title,description,active,children}:{title:string;description:string;active:string;children:ReactNode}){const nav=[["▦","Resumen","/dashboard"],["↔","Exchanges","/dashboard/exchanges"],["≋","Movimientos","/dashboard/movimientos"],["€","Fiscalidad","/dashboard/fiscalidad"],["▣","Informes","/dashboard/informes"],["?","Ayuda","/dashboard/ayuda"],["⚙","Configuración","/dashboard/configuracion"]];return <div className="app-shell"><aside className="app-sidebar"><Link className="app-logo" href="/dashboard"><span className="brand-mark">₿</span><span className="brand-name">Coin<span>Renta</span></span></Link><nav className="app-nav">{nav.map(([icon,label,href])=><Link className={`app-nav-item ${label.toLowerCase().startsWith(active)?"active":""}`} href={href} key={href}><span>{icon}</span>{label}</Link>)}</nav></aside><main className="app-main"><header className="app-topbar"><div><span className="topbar-kicker">CoinRenta</span><h1>{title}</h1><p>{description}</p></div></header><section className="dashboard-content">{children}</section></main></div>}
function Empty({text}:{text:string}){return <div className="empty-state"><strong>{text}</strong><p>Cuando añadas datos, aparecerán aquí automáticamente.</p></div>}
