import type { Metadata } from "next";
import Link from "next/link";
import LegalPage from "@/components/legal-page";

export const metadata: Metadata = { title: "Aviso legal", description: "Información legal e identificativa de CoinRenta." };

const P = ({ children }: { children: React.ReactNode }) => <p>{children}</p>;

export default function LegalNoticePage() {
  return <LegalPage label="Información jurídica" title="Aviso legal" intro="Información sobre el titular, las condiciones de acceso, las responsabilidades y el marco de uso del sitio web y de los servicios de CoinRenta." updated="16 de septiembre de 2026" activePath="/legal/aviso-legal" sections={[
    { title: "1. Datos identificativos y contacto", children: <><P><strong>Nombre o razón social:</strong> el titular legal de CoinRenta debe figurar aquí con su denominación completa.</P><P><strong>Nombre comercial:</strong> CoinRenta.</P><P><strong>Domicilio completo:</strong> debe figurar aquí el domicilio legal del titular.</P><P><strong>Correo electrónico:</strong> info@coinrenta.es.</P><P><strong>Teléfono:</strong> debe figurar aquí el número habilitado para el contacto cuando resulte exigible.</P><P>Los datos identificativos completos del titular son información legal obligatoria y deben mantenerse actualizados. No se sustituyen por el nombre comercial del proyecto.</P></> },
    { title: "2. Objeto y ámbito", children: <P>Este sitio web ofrece información sobre CoinRenta y permite acceder a herramientas digitales destinadas a organizar, importar, analizar y consultar información relacionada con activos digitales. El acceso y uso del sitio implican la aceptación de las condiciones legales aplicables y no convierten a CoinRenta en un proveedor de servicios financieros o de criptoactivos por el mero hecho de tratar información sobre estos activos.</P> },
    { title: "3. Naturaleza del servicio", children: <><P>CoinRenta es una herramienta tecnológica de organización y análisis de información. No presta por sí misma, salvo que en el futuro se anuncie expresamente y se obtengan las autorizaciones que correspondan, servicios de custodia, intermediación, ejecución de órdenes, asesoramiento sobre inversión, gestión de carteras, recepción o transmisión de órdenes ni otros servicios regulados sobre criptoactivos.</P><P>La regulación aplicable a los proveedores de servicios de criptoactivos exige autorización en los supuestos previstos legalmente. CoinRenta no debe presentarse como un proveedor autorizado de tales servicios si no dispone de la autorización correspondiente.</P></> },
    { title: "4. Información fiscal y financiera", children: <><P>Los cálculos, clasificaciones y contenidos fiscales de CoinRenta tienen finalidad informativa y de apoyo a la organización de datos. No constituyen asesoramiento fiscal, contable, jurídico ni financiero individualizado.</P><P>La persona usuaria debe comprobar los resultados y, cuando proceda, consultar a un profesional cualificado antes de presentar una declaración tributaria o adoptar una decisión con consecuencias fiscales o financieras.</P></> },
    { title: "5. Exactitud de la información", children: <P>CoinRenta procura mantener la información y las herramientas actualizadas, pero la exactitud final puede depender de los datos suministrados por el usuario, de los exchanges, de archivos CSV, de precios de mercado, de cambios normativos y de incidencias técnicas. No debe entenderse que la información mostrada garantiza un resultado fiscal concreto.</P> },
    { title: "6. Conexiones con terceros", children: <P>El usuario puede conectar servicios externos o importar archivos. Dichas conexiones se realizan bajo la autorización del usuario y están sujetas a las condiciones y políticas de privacidad de cada proveedor externo. CoinRenta no controla los servicios de terceros ni responde de sus cambios, interrupciones o errores independientes.</P> },
    { title: "7. Contratación y consumidores", children: <><P>Cuando CoinRenta ofrezca planes de pago a consumidores, antes de la contratación se facilitará de forma clara, comprensible y accesible la información precontractual legalmente exigible, incluyendo la identidad del empresario, las características principales del servicio, el precio total con los impuestos aplicables, la duración, la renovación cuando exista, las condiciones de cancelación y el derecho de desistimiento o su eventual excepción legal.</P><P>Las condiciones de uso y contratación, así como la <Link href="/legal/devoluciones">Política de desistimiento y devoluciones</Link>, forman parte de la documentación legal disponible antes y durante la contratación.</P></> },
    { title: "8. Propiedad intelectual", children: <P>El diseño, código, contenidos, logotipos, textos, elementos gráficos y demás materiales de CoinRenta están protegidos por la normativa aplicable sobre propiedad intelectual e industrial. Salvo autorización legal o del titular, no se permite su reproducción, distribución, comunicación pública, transformación o explotación fuera del uso legítimo del servicio.</P> },
    { title: "9. Conducta prohibida", children: <P>Queda prohibido utilizar CoinRenta para fines ilícitos, intentar obtener acceso no autorizado a cuentas o sistemas, introducir código malicioso, interferir en la disponibilidad del servicio, eludir controles de seguridad o utilizar las integraciones de terceros de forma contraria a sus condiciones.</P> },
    { title: "10. Enlaces externos", children: <P>Cuando el sitio incluya enlaces a webs o servicios de terceros, estos se facilitan por utilidad informativa. CoinRenta no controla su contenido ni sus políticas y no asume responsabilidad por ellos, sin perjuicio de las obligaciones que legalmente correspondan.</P> },
    { title: "11. Responsabilidad", children: <P>Dentro de los límites permitidos por la ley, CoinRenta no será responsable de daños derivados de un uso contrario a estas condiciones, de información incorrecta aportada por terceros o por el usuario, de decisiones adoptadas exclusivamente sobre la base de cálculos informativos, ni de interrupciones provocadas por proveedores externos o causas de fuerza mayor. Esta limitación no excluye responsabilidades que legalmente no puedan limitarse ni los derechos de consumidores en materia de conformidad y contratación.</P> },
    { title: "12. Legislación y jurisdicción", children: <P>La prestación de servicios y el uso del sitio se regirán por la legislación española y de la Unión Europea que resulte aplicable. Cuando la persona usuaria tenga la condición legal de consumidora, se respetarán las normas imperativas de protección de consumidores y las reglas de jurisdicción que correspondan.</P> },
    { title: "13. Contacto", children: <P>Para consultas sobre el sitio, el servicio o sus condiciones legales: <strong>info@coinrenta.es</strong>.</P> },
  ]} />;
}
