import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import QualityControl from "./quality-control";

export const metadata: Metadata = { title: "Renta", description: "Preparación fiscal de criptoactivos.", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

type Tx={id:string;occurred_at:string;transaction_type:string;base_asset_id:string|null;base_amount:number|string|null;quote_asset_id:string|null;quote_amount:number|string|null;fee_asset_id:string|null;fee_amount:number|string|null;price:number|string|null;price_currency:string|null;source:string|null;account_id:string};
type Snapshot={id:string;captured_at:string;account_id:string;asset_id:string;quantity:number|string|null;value_eur:number|string|null;price_eur:number|string|null;source:string|null};
type Asset={id:string;symbol:string;name:string;asset_type:string|null};
type Account={id:string;connection_id:string|null;name:string};
type Connection={id:string;exchange_id:string;label:string|null;provider_type:string|null};
type Exchange={id:string;code:string;name:string;website:string|null};
type Lot={qty:number;cost:number|null};
type Sale={id:string;occurredAt:string;symbol:string;name:string;quantity:number;proceeds:number|null;missingQuantity:number;reason:string};
type Report={disposals:number;proceeds:number;costBasis:number;gain:number;gainKnown:boolean;unknownBasis:number;incomeEur:number;incomeKnown:number;feesEur:number;cryptoFeeEvents:number;transfers:number;unsupported:number;qualitySales:Sale[];positions:{symbol:string;name:string;quantity:number;valueEur:number|null;accountCount:number;foreign:boolean}[];foreignValueEur:number};

const FIAT=new Set(["EUR","USD","GBP","CHF","PLN","SEK","DKK","NOK"]);
const INCOME=new Set(["reward","interest","dividend","airdrop","cashback","staking"]);
const TRANSFERS=new Set(["deposit","withdrawal","transfer_in","transfer_out","transfer"]);
const SALES=new Set(["sell","swap","trade","convert"]);
const money=(v:number|null|undefined)=>v==null||!Number.isFinite(v)?"—":v.toLocaleString("es-ES",{style:"currency",currency:"EUR",maximumFractionDigits:2});
const qty=(v:number)=>v.toLocaleString("es-ES",{maximumFractionDigits:8});
const date=(v:string|null|undefined)=>v?new Intl.DateTimeFormat("es-ES",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const startOf=(y:number)=>`${y}-01-01T00:00:00.000Z`;
const endOf=(y:number)=>`${y+1}-01-01T00:00:00.000Z`;

async function getTransactions(db:Awaited<ReturnType<typeof createClient>>,userId:string,end:string){const rows:Tx[]=[];for(let from=0;;from+=1000){const {data,error}=await db.from("transactions").select("id,occurred_at,transaction_type,base_asset_id,base_amount,quote_asset_id,quote_amount,fee_asset_id,fee_amount,price,price_currency,source,account_id").eq("user_id",userId).lt("occurred_at",end).order("occurred_at",{ascending:true}).range(from,from+999);if(error)throw new Error(error.message);const page=(data||[]) as Tx[];rows.push(...page);if(page.length<1000)return rows;}}

function reportFor(txs:Tx[],year:number,assets:Map<string,Asset>,accounts:Map<string,Account>,connections:Map<string,Connection>,exchanges:Map<string,Exchange>,snapshots:Snapshot[]):Report{
 const lots=new Map<string,Lot[]>(),sales:Sale[]=[],positions=new Map<string,{symbol:string;name:string;quantity:number;accounts:Set<string}>/>(),pending=new Map<string,{cost:number;at:number}>();
 let disposals=0,proceeds=0,costBasis=0,gain=0,unknownBasis=0,incomeEur=0,incomeKnown=0,feesEur=0,cryptoFeeEvents=0,transfers=0,unsupported=0,gainKnown=true;
 const asset=(id:string|null)=>id?assets.get(id)||null:null;
 const add=(id:string,q:number,c:number|null)=>{if(q<=0)return;const a=lots.get(id)||[];a.push({qty:q,cost:c});lots.set(id,a);};
 const take=(id:string,q:number)=>{let rem=q,allocated=0,known=true;const a=lots.get(id)||[];while(rem>1e-12&&a.length){const l=a[0],n=Math.min(rem,l.qty);if(l.cost==null)known=false;else allocated+=l.cost*(n/l.qty);l.qty-=n;rem-=n;if(l.qty<=1e-12)a.shift();}lots.set(id,a);return{allocated,known,remaining:rem};};
 for(const tx of [...txs].sort((a,b)=>new Date(a.occurred_at).getTime()-new Date(b.occurred_at).getTime())){
  const type=String(tx.transaction_type||"").toLowerCase(),base=asset(tx.base_asset_id),quote=asset(tx.quote_asset_id),feeAsset=asset(tx.fee_asset_id);const bq=Math.abs(Number(tx.base_amount||0)),qv=Math.abs(Number(tx.quote_amount||0)),fq=Math.abs(Number(tx.fee_amount||0)),inYear=new Date(tx.occurred_at).getUTCFullYear()===year;const quoteEur=!!quote&&((quote.asset_type==="fiat"&&quote.symbol.toUpperCase()==="EUR")||(tx.price_currency||"").toUpperCase()==="EUR");const quoteFiat=!!quote&&(quote.asset_type==="fiat"||FIAT.has(quote.symbol.toUpperCase()));
  if(fq>0){if(feeAsset&&!FIAT.has(feeAsset.symbol.toUpperCase())&&feeAsset.asset_type!=="fiat"){if(inYear)cryptoFeeEvents++;}else if(inYear)feesEur+=fq;}
  if(type==="buy"&&base&&bq){const cost=qv&&quoteFiat&&quoteEur?qv+((feeAsset&&FIAT.has(feeAsset.symbol.toUpperCase()))?fq:0):null;add(base.id,bq,cost);continue;}
  if(INCOME.has(type)&&base&&bq){const value=qv&&quoteEur?qv:(Number(tx.price)>0&&(tx.price_currency||"").toUpperCase()==="EUR"?bq*Number(tx.price):null);if(inYear&&value!=null){incomeEur+=value;incomeKnown++;}add(base.id,bq,value);continue;}
  if(TRANSFERS.has(type)){if(inYear)transfers++;if((type==="transfer_out"||type==="withdrawal")&&base&&bq){const r=take(base.id,bq);if(r.remaining<=1e-12)pending.set(`${base.id}:${bq.toFixed(12)}`,{cost:r.allocated,at:new Date(tx.occurred_at).getTime()});}else if((type==="transfer_in"||type==="deposit"||type==="transfer")&&base&&bq){const k=`${base.id}:${bq.toFixed(12)}`,p=pending.get(k);if(p&&Math.abs(new Date(tx.occurred_at).getTime()-p.at)<=7*86400000){add(base.id,bq,p.cost);pending.delete(k);}else add(base.id,bq,null);}continue;}
  if(type==="fee"){if(feeAsset&&fq)take(feeAsset.id,fq);else if(base&&bq)take(base.id,bq);continue;}
  if(type==="expense")continue;
  if(SALES.has(type)&&base&&bq){const r=take(base.id,bq);if(!quoteFiat&&!quoteEur){if(inYear)unsupported++;if(r.remaining>1e-12)gainKnown=false;if(quote)add(quote.id,qv,null);continue;}if(inYear){disposals++;const net=qv-((feeAsset&&(feeAsset.asset_type==="fiat"||FIAT.has(feeAsset.symbol.toUpperCase())))?fq:0);if(qv&&quoteEur){proceeds+=net;if(r.known){costBasis+=r.allocated;gain+=net-r.allocated;}else{gainKnown=false;unknownBasis++;sales.push({id:tx.id,occurredAt:tx.occurred_at,symbol:base.symbol,name:base.name,quantity:bq,proceeds:net,missingQuantity:r.remaining>1e-12?r.remaining:bq,reason:r.remaining>1e-12?"No hay cantidad adquirida suficiente en los datos importados.":"El lote FIFO contiene un coste de adquisición no demostrable."});}}else{gainKnown=false;unknownBasis++;sales.push({id:tx.id,occurredAt:tx.occurred_at,symbol:base.symbol,name:base.name,quantity:bq,proceeds:null,missingQuantity:bq,reason:"La contraprestación de la venta no está suficientemente identificada."});}}continue;}
  if(base&&bq&&type!=="unknown"){if(inYear)unsupported++;add(base.id,bq,null);}
 }
 for(const [id,ls] of lots){const a=assets.get(id);if(!a)continue;const quantity=ls.reduce((s,l)=>s+Math.max(0,l.qty),0);if(quantity<=1e-12)continue;const accountSet=new Set<string>();for(const s of snapshots)if(s.asset_id===id&&Math.abs(Number(s.quantity||0))>1e-12)accountSet.add(s.account_id);positions.set(id,{symbol:a.symbol,name:a.name,quantity,accounts:accountSet});}
 const yearEnd=snapshots.filter(s=>{const d=new Date(s.captured_at);return d.getUTCFullYear()===year&&d.getUTCMonth()===11&&d.getUTCDate()===31&&s.value_eur!=null});const values=new Map<string,number>(),foreign=new Set<string>();let foreignValueEur=0;for(const s of yearEnd){const v=Number(s.value_eur);if(!Number.isFinite(v))continue;values.set(s.asset_id,(values.get(s.asset_id)||0)+v);const account=accounts.get(s.account_id),connection=account?.connection_id?connections.get(account.connection_id):null,exchange=connection?exchanges.get(connection.exchange_id):null;if(exchange?.code.toLowerCase()==="bitpanda"){foreignValueEur+=v;foreign.add(s.asset_id);}}
 const pos=[...positions.entries()].map(([id,p])=>({symbol:p.symbol,name:p.name,quantity:p.quantity,valueEur:values.get(id)||null,accountCount:p.accounts.size,foreign:foreign.has(id)})).sort((a,b)=>(b.valueEur||0)-(a.valueEur||0));
 return{disposals,proceeds,costBasis,gain,gainKnown,unknownBasis,incomeEur,incomeKnown,feesEur,cryptoFeeEvents,transfers,unsupported,qualitySales:sales,positions:pos,foreignValueEur};
}

export default async function RentaPage({searchParams}:{searchParams:Promise<{year?:string}>}){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login");const p=await searchParams;const requested=Number(p.year);const year=Number.isInteger(requested)&&requested>=2020&&requested<=2030?requested:2025;const end=endOf(year);
 const [txs,snapshotsResult,latestResult,assetsResult,accountsResult,connectionsResult,exchangesResult,taxResult]=await Promise.all([getTransactions(db,user.id,end),db.from("balance_snapshots").select("id,captured_at,account_id,asset_id,quantity,value_eur,price_eur,source").eq("user_id",user.id).lt("captured_at",end).order("captured_at",{ascending:true}).limit(20000),db.from("balance_snapshots").select("captured_at,source").eq("user_id",user.id).order("captured_at",{ascending:false}).limit(1).maybeSingle(),db.from("assets").select("id,symbol,name,asset_type"),db.from("accounts").select("id,connection_id,name").eq("user_id",user.id),db.from("exchange_connections").select("id,exchange_id,label,provider_type").eq("user_id",user.id),db.from("exchanges").select("id,code,name,website").eq("is_active",true),db.from("tax_years").select("id,year,status,updated_at").eq("user_id",user.id).order("year",{ascending:false})]);
 const err=snapshotsResult.error||latestResult.error||assetsResult.error||accountsResult.error||connectionsResult.error||exchangesResult.error;if(err)throw new Error(err.message);
 const snapshots=(snapshotsResult.data||[]) as Snapshot[],assets=new Map<string,Asset>((assetsResult.data||[]).map((r:Asset)=>[r.id,r])),accounts=new Map<string,Account>((accountsResult.data||[]).map((r:Account)=>[r.id,r])),connections=new Map<string,Connection>((connectionsResult.data||[]).map((r:Connection)=>[r.id,r])),exchanges=new Map<string,Exchange>((exchangesResult.data||[]).map((r:Exchange)=>[r.id,r])),report=reportFor(txs,year,assets,accounts,connections,exchanges,snapshots);
 const latest=latestResult.data?.captured_at||null,yearEnd=snapshots.some(s=>{const d=new Date(s.captured_at);return d.getUTCFullYear()===year&&d.getUTCMonth()===11&&d.getUTCDate()===31&&s.value_eur!=null}),foreignCustodians=[...connections.values()].filter(c=>exchanges.get(c.exchange_id)?.code.toLowerCase()==="bitpanda"),partial=!report.gainKnown;
 const issues=[report.unknownBasis?{code:"missing-basis",title:`${report.unknownBasis} ventas con coste de adquisición no demostrable`,description:"El coste FIFO de estas ventas no puede justificarse completamente con los datos importados.",sales:report.qualitySales}:null,report.unsupported?{code:"unsupported",title:`${report.unsupported} operaciones requieren clasificación`,description:"Se han conservado los movimientos, pero alguno necesita una clasificación que CoinRenta todavía no puede determinar con seguridad.",actionLabel:"Revisar movimientos",actionHref:"/dashboard/movimientos"}:null,report.cryptoFeeEvents?{code:"crypto-fees",title:`${report.cryptoFeeEvents} comisiones pagadas en cripto`,description:"Estas comisiones pueden constituir una disposición y se mantienen separadas para su tratamiento.",actionLabel:"Revisar movimientos",actionHref:"/dashboard/movimientos"}:null,!yearEnd?{code:"info",title:"No hay valoración exacta a 31/12",description:"La valoración patrimonial del ejercicio no se considera definitiva sin un cierre de valoración de ese día."}:null,foreignCustodians.length?{code:"info-foreign",title:"Se ha detectado custodia extranjera",description:"Comprueba la entidad contractual del custodio antes de determinar las obligaciones informativas aplicables."}:null].filter(Boolean) as any[];
 const actionable=issues.filter(i=>i.code!=="info"&&i.code!=="info-foreign"),links=[2025,2024,2023,2022].map(y=>({y,href:y===2025?"/dashboard/renta":`/dashboard/renta?year=${y}`})),taxYear=(taxResult.data||[]).find((x:any)=>x.year===year);
 return (<><header className="app-topbar"><div><span className="topbar-kicker">CoinRenta</span><h1>Renta</h1><p>Preparación de datos para IRPF, Patrimonio, Modelo 721 y trazabilidad DAC8/CARF.</p></div></header><main className="dashboard-content renta-page">
  <section className="renta-hero panel-card"><div><span className="section-kicker">EJERCICIO FISCAL</span><h2>Informe fiscal {year}</h2><p>Los importes se calculan únicamente con la información disponible en CoinRenta.</p><div className="renta-valuation-meta"><span>Fecha de valoración: <strong>{date(latest)}</strong></span><span>{latest?"Última valoración registrada":"Sin valoración registrada"}</span></div></div><nav className="renta-year-switcher" aria-label="Ejercicio fiscal">{links.map(x=><Link key={x.y} href={x.href} className={x.y===year?"selected":""}>{x.y}</Link>)}</nav></section>
  <section className="renta-stat-grid"><article className={`stat-card ${partial?"stat-card-warning":""}`}><span className="stat-label">Ganancia / pérdida cripto</span><strong className={partial?"renta-number-warning":""}>{money(report.gain)}</strong><span className="stat-note">{partial?"Cálculo parcial: se excluyen operaciones pendientes de revisión.":"Cálculo realizado con los lotes disponibles."}</span>{partial&&<small className="renta-warning-inline">Resultado provisional y meramente informativo; no es vinculante.</small>}</article><article className="stat-card"><span className="stat-label">Valor de transmisión</span><strong>{money(report.proceeds)}</strong><span className="stat-note">Contraprestación EUR identificada</span></article><article className="stat-card"><span className="stat-label">Coste de adquisición</span><strong>{money(report.costBasis)}</strong><span className="stat-note">Lotes FIFO demostrables</span></article><article className={`stat-card ${actionable.length?"stat-card-accent":""}`}><span className="stat-label">Acciones pendientes</span><strong>{actionable.length}</strong><span className="stat-note">Solo incidencias que requieren intervención</span></article></section>
  <section className="renta-section panel-card"><div className="panel-head"><div><span className="section-kicker">MODELO 100 · IRPF</span><h3>Ganancias y pérdidas patrimoniales</h3></div><span className="renta-badge">Renta del ahorro</span></div><div className="renta-summary-grid"><div><small>Transmisiones / permutas</small><strong>{report.disposals}</strong></div><div><small>Ganancia calculada</small><strong className={partial?"renta-number-warning":""}>{money(report.gain)}</strong></div><div><small>Ingresos identificados</small><strong>{report.incomeKnown?money(report.incomeEur):"Parcial"}</strong></div><div><small>Comisiones fiat</small><strong>{money(report.feesEur)}</strong></div></div><div className="renta-explanation"><strong>Resultado del cálculo</strong><span>Cuando existen operaciones que requieren revisión, CoinRenta conserva y muestra la ganancia que sí puede calcularse y excluye del resultado las operaciones cuyo coste o contraprestación no puede justificarse.</span></div><div className="renta-table-wrap"><table><thead><tr><th>Magnitud</th><th>Resultado</th><th>Estado</th></tr></thead><tbody><tr><td>Valor de transmisión</td><td>{money(report.proceeds)}</td><td><span className="renta-status ok">Calculado</span></td></tr><tr><td>Coste de adquisición</td><td>{money(report.costBasis)}</td><td><span className={`renta-status ${report.unknownBasis?"warn":"ok"}`}>{report.unknownBasis?"Parcial":"FIFO"}</span></td></tr><tr><td>Ganancia / pérdida</td><td className={partial?"renta-number-warning":""}>{money(report.gain)}</td><td><span className={`renta-status ${partial?"warn":"ok"}`}>{partial?"Provisional":"Calculada"}</span></td></tr></tbody></table></div>{partial&&<div className="renta-provisional"><strong>Advertencia sobre el resultado</strong><span>La cifra no incorpora las operaciones pendientes de revisión. Es orientativa, no vinculante y debe contrastarse con la documentación original.</span></div>}</section>
  <section className="renta-section panel-card"><div className="panel-head"><div><span className="section-kicker">PATRIMONIO · 31 DE DICIEMBRE</span><h3>Inventario patrimonial</h3></div><span className={`renta-badge ${yearEnd?"positive":"warning"}`}>{yearEnd?"Valoración disponible":"Valoración pendiente"}</span></div><div className="renta-summary-grid three"><div><small>Activos con saldo</small><strong>{report.positions.length}</strong></div><div><small>Valor conocido 31/12</small><strong>{money(report.positions.reduce((s,x)=>s+(x.valueEur||0),0))}</strong></div><div><small>Fecha de valoración</small><strong>{date(latest)}</strong></div></div>{report.positions.length?<div className="renta-table-wrap"><table><thead><tr><th>Activo</th><th>Saldo</th><th>Valor EUR</th><th>Custodia</th></tr></thead><tbody>{report.positions.map(x=><tr key={x.symbol}><td><strong>{x.name}</strong><small>{x.symbol}</small></td><td>{qty(x.quantity)}</td><td>{money(x.valueEur)}</td><td>{x.foreign?"Custodia extranjera":"Revisar ubicación"}</td></tr>)}</tbody></table></div>:<div className="renta-empty">No hay posiciones calculables con los datos disponibles.</div>}<p className="renta-note">La fecha mostrada corresponde a la última valoración registrada; para ejercicios históricos no equivale necesariamente al cierre fiscal de 31/12.</p></section>
  <section className="renta-section panel-card"><div className="panel-head"><div><span className="section-kicker">MODELO 721</span><h3>Comprobación de activos en el extranjero</h3></div><span className={`renta-badge ${report.foreignValueEur>50000?"warning":""}`}>{report.foreignValueEur>50000?"Umbral superado":"Por debajo de 50.000 €"}</span></div><div className="renta-summary-grid three"><div><small>Saldo extranjero conocido</small><strong>{money(report.foreignValueEur)}</strong></div><div><small>Custodios extranjeros</small><strong>{foreignCustodians.length}</strong></div><div><small>Estado</small><strong>{report.foreignValueEur>50000?"Revisar Modelo 721":"Sin superación detectada"}</strong></div></div><p className="renta-note">El resultado depende de los datos de custodia y valoración disponibles en la aplicación y debe verificarse con la situación real del contribuyente.</p></section>
  <section className="renta-section panel-card"><div className="panel-head"><div><span className="section-kicker">DAC8 · CARF · MiCA</span><h3>Trazabilidad regulatoria</h3></div><span className="renta-badge neutral">Información contextual</span></div><div className="renta-framework-grid"><div><strong>DAC8</strong><span>La información se conserva para facilitar la trazabilidad de usuarios, activos y operaciones comunicables.</span></div><div><strong>CARF</strong><span>Las operaciones, transferencias e ingresos se mantienen diferenciados para facilitar su conciliación.</span></div><div><strong>MiCA</strong><span>Se utiliza como referencia del marco regulatorio de proveedores; no determina por sí mismo el IRPF.</span></div></div></section>
  <section className="renta-section panel-card"><div className="panel-head"><div><span className="section-kicker">CONTROL DE CALIDAD</span><h3>{actionable.length?"Hay incidencias que requieren revisión":"Datos preparados para revisión"}</h3></div><span className={`renta-badge ${actionable.length?"warning":"positive"}`}>{actionable.length?`${actionable.length} acciones pendientes":"Sin acciones pendientes"}</span></div><QualityControl issues={issues}/><div className="renta-data-foot"><span>Transacciones del ejercicio: <strong>{txs.filter(t=>new Date(t.occurred_at)>=new Date(startOf(year))).length}</strong></span><span>Históricas analizadas: <strong>{txs.length}</strong></span><span>Última actualización fiscal: <strong>{taxYear?.updated_at?date(taxYear.updated_at):"No registrada"}</strong></span></div></section>
  <section className="renta-disclaimer"><strong>Aviso importante sobre el carácter exclusivamente informativo</strong><p>Los datos, cálculos, estimaciones y resultados ofrecidos por CoinRenta tienen carácter exclusivamente informativo y orientativo. CoinRenta no presta servicios de asesoramiento fiscal, contable ni jurídico y la aplicación no sustituye la revisión de la documentación original ni el asesoramiento de un profesional cualificado. La información importada puede contener errores, omisiones, limitaciones de formato o datos incompletos, y los cálculos pueden no contemplar todas las circunstancias particulares del contribuyente. El usuario debe verificar la información y sus obligaciones tributarias antes de utilizar cualquier resultado en una declaración. CoinRenta no garantiza que los resultados sean exactos, completos o adecuados para una situación fiscal concreta y no asume responsabilidad por decisiones, declaraciones, liquidaciones, sanciones, recargos, intereses o cualquier otro perjuicio que pudiera derivarse del uso de la información proporcionada por la aplicación.</p></section>
 </main></>);
}
