import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "Revisar lote · Renta", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

function date(value:string){return new Intl.DateTimeFormat("es-ES",{dateStyle:"short",timeStyle:"short"}).format(new Date(value));}
function amount(value:number|string|null){const n=Number(value);return Number.isFinite(n)?n.toLocaleString("es-ES",{maximumFractionDigits:8}):"—";}
function money(value:number|string|null){const n=Number(value);return Number.isFinite(n)?n.toLocaleString("es-ES",{style:"currency",currency:"EUR",maximumFractionDigits:2}):"—";}

export default async function ReviewLotPage({searchParams}:{searchParams:Promise<{asset?:string;before?:string;sale?:string}>}){
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const params=await searchParams;const symbol=(params.asset||"").trim().toUpperCase();const before=params.before||"";
  if(!symbol)return <main className="dashboard-content"><section className="panel-card"><h2>No se ha indicado el activo</h2><Link className="btn btn-primary" href="/dashboard/renta">Volver a Renta</Link></section></main>;
  const {data:asset}=await supabase.from("assets").select("id,symbol,name").eq("symbol",symbol).maybeSingle();
  if(!asset)return <main className="dashboard-content"><section className="panel-card"><h2>Activo no encontrado</h2><p>No existe un activo con símbolo {symbol} en los datos importados.</p><Link className="btn btn-primary" href="/dashboard/renta">Volver a Renta</Link></section></main>;
  const query=supabase.from("transactions").select("id,occurred_at,transaction_type,base_amount,quote_amount,fee_amount,price,price_currency,source,external_id,raw_data,accounts(name),quote:assets!transactions_quote_asset_id_fkey(symbol),fee:assets!transactions_fee_asset_id_fkey(symbol)").eq("user_id",user.id).eq("base_asset_id",asset.id).order("occurred_at",{ascending:false}).limit(100);
  const {data:transactions,error}=before?await query.lt("occurred_at",before):await query;
  const acquisitions=(transactions||[]).filter((tx:any)=>["buy","deposit","transfer_in","reward","interest","airdrop","cashback"].includes(String(tx.transaction_type||"").toLowerCase()));
  return <><header className="app-topbar"><div><span className="topbar-kicker">CoinRenta · Control de calidad</span><h1>Revisar lote de {asset.symbol}</h1><p>Movimientos anteriores a la venta afectada. Aquí puedes comprobar si el CSV importado contiene el origen del coste.</p></div></header><section className="dashboard-content renta-page"><section className="renta-section panel-card"><div className="panel-head"><div><span className="section-kicker">ACTIVO</span><h3>{asset.name} · {asset.symbol}</h3></div><Link className="quality-action primary" href="/dashboard/exchanges">Importar CSV</Link></div><div className="renta-explanation"><strong>Qué estás buscando</strong><span>Una compra, depósito con coste demostrable, reward valorado u otro movimiento que permita justificar la adquisición de la cantidad vendida. Los depósitos/transferencias sin coste no se convierten automáticamente en un coste inventado.</span></div>{error?<div className="connection-error">No se pudieron cargar los movimientos: {error.message}</div>:transactions?.length?<div className="renta-table-wrap"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Cantidad</th><th>Contrapartida</th><th>Fee</th><th>Origen</th></tr></thead><tbody>{transactions.map((tx:any)=><tr key={tx.id}><td>{date(tx.occurred_at)}</td><td><strong>{tx.transaction_type}</strong></td><td>{amount(tx.base_amount)} {asset.symbol}</td><td>{amount(tx.quote_amount)} {tx.quote?.symbol||tx.price_currency||""}</td><td>{amount(tx.fee_amount)} {tx.fee?.symbol||""}</td><td>{tx.source||"—"}</td></tr>)}</tbody></table></div>:<div className="renta-empty">No hay movimientos anteriores de {asset.symbol} en los datos importados. Esto es un indicio claro de que falta histórico o que el origen está en otro exchange/wallet.</div>}</section><section className="renta-section panel-card"><div className="panel-head"><div><span className="section-kicker">CANDIDATOS A ADQUISICIÓN</span><h3>{acquisitions.length} movimientos candidatos</h3></div></div>{acquisitions.length?<div className="renta-table-wrap"><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Cantidad</th><th>Importe</th></tr></thead><tbody>{acquisitions.map((tx:any)=><tr key={tx.id}><td>{date(tx.occurred_at)}</td><td>{tx.transaction_type}</td><td>{amount(tx.base_amount)} {asset.symbol}</td><td>{money(tx.quote_amount)} {tx.price_currency||""}</td></tr>)}</tbody></table></div>:<div className="renta-empty">No se ha encontrado ningún candidato a adquisición. Importa el histórico completo del exchange que originó esta posición.</div>}<div className="quality-actions"><Link className="quality-action secondary" href="/dashboard/renta">Volver al control de calidad</Link><Link className="quality-action primary" href="/dashboard/exchanges">Añadir / importar otro CSV</Link></div></section></section></>;
}
