"use client";

import Image from "next/image";
import { useEffect, useState } from "react";

const MESSAGES = ["Preparando tu espacio fiscal","Cargando tu histórico","Verificando movimientos","Calculando resultados"];

type Props = { duration?: number; onComplete?: () => void; contained?: boolean };

export default function CoinRentaLoader({ duration = 3000, onComplete, contained = false }: Props) {
  const [messageIndex, setMessageIndex] = useState(0);
  useEffect(() => {
    const interval = window.setInterval(() => setMessageIndex((value) => (value + 1) % MESSAGES.length), 650);
    const timer = window.setTimeout(() => onComplete?.(), duration);
    return () => { window.clearInterval(interval); window.clearTimeout(timer); };
  }, [duration, onComplete]);

  return <div className={`coinrenta-loader${contained ? " coinrenta-loader-contained" : ""}`} aria-live="polite" aria-busy="true">
    <style>{`
      .coinrenta-loader{position:fixed;inset:0;z-index:99999;display:grid;place-items:center;overflow:hidden;background:#050a12;isolation:isolate;animation:cr-loader-in .28s ease-out both}
      .coinrenta-loader-contained{position:absolute;inset:0;z-index:100;min-height:100dvh;height:100dvh;max-height:100dvh;overflow:hidden;border-radius:0}
      .coinrenta-loader::before{content:"";position:absolute;inset:-24%;background:radial-gradient(circle at 50% 42%,rgba(20,203,191,.18),transparent 21%),radial-gradient(circle at 22% 72%,rgba(25,122,177,.12),transparent 23%),radial-gradient(circle at 78% 25%,rgba(112,81,191,.10),transparent 21%);filter:blur(20px);animation:cr-loader-aurora 7s ease-in-out infinite alternate}
      .coinrenta-loader::after{content:"";position:absolute;inset:0;background:linear-gradient(115deg,transparent 18%,rgba(255,255,255,.035) 50%,transparent 82%);transform:translateX(-120%);animation:cr-loader-sheen 2.6s ease-in-out infinite}
      .coinrenta-loader-orbit{position:absolute;width:min(68vw,760px);height:min(68vw,760px);border-radius:50%;border:1px solid rgba(109,224,215,.12);box-shadow:0 0 110px rgba(15,167,160,.10),inset 0 0 80px rgba(15,167,160,.035);animation:cr-loader-orbit 14s linear infinite}.coinrenta-loader-orbit::before,.coinrenta-loader-orbit::after{content:"";position:absolute;border-radius:50%;border:1px solid rgba(109,224,215,.075)}.coinrenta-loader-orbit::before{inset:7%;animation:cr-loader-spin-reverse 9s linear infinite}.coinrenta-loader-orbit::after{inset:18%;border-right-color:rgba(109,224,215,.28);animation:cr-loader-spin 6s linear infinite}
      .coinrenta-loader-particle{position:absolute;width:5px;height:5px;border-radius:50%;background:#6de0d7;box-shadow:0 0 14px rgba(109,224,215,.75);animation:cr-loader-particle 4.5s ease-in-out infinite}.coinrenta-loader-particle.a{left:28%;top:27%}.coinrenta-loader-particle.b{right:25%;top:34%;animation-delay:-1.4s}.coinrenta-loader-particle.c{left:23%;bottom:26%;animation-delay:-2.6s}.coinrenta-loader-particle.d{right:29%;bottom:22%;animation-delay:-3.6s}
      .coinrenta-loader-card{position:relative;z-index:2;display:flex;flex-direction:column;align-items:center;text-align:center;width:min(570px,calc(100vw - 38px));padding:42px 30px 32px;border:1px solid rgba(255,255,255,.10);border-radius:28px;background:linear-gradient(155deg,rgba(13,24,40,.82),rgba(7,13,23,.76));box-shadow:0 35px 110px rgba(0,0,0,.42),inset 0 1px 0 rgba(255,255,255,.045);backdrop-filter:blur(20px);animation:cr-loader-card 4.5s ease-in-out infinite}
      .coinrenta-loader-logo-wrap{position:relative;width:118px;height:118px;display:grid;place-items:center;margin-bottom:18px}.coinrenta-loader-logo-wrap::before{content:"";position:absolute;inset:-12px;border-radius:50%;background:radial-gradient(circle,rgba(109,224,215,.22),transparent 62%);filter:blur(5px);animation:cr-loader-glow 2s ease-in-out infinite}.coinrenta-loader-ring{position:absolute;inset:-3px;border-radius:50%;border:1px solid rgba(109,224,215,.19);border-top-color:#6de0d7;border-right-color:rgba(109,224,215,.55);animation:cr-loader-spin 2s linear infinite}.coinrenta-loader-ring.two{inset:11px;border-color:rgba(109,224,215,.10);border-bottom-color:#27c9bf;animation:cr-loader-spin-reverse 1.55s linear infinite}.coinrenta-loader-logo{position:relative;width:90px;height:90px;object-fit:contain;filter:drop-shadow(0 16px 32px rgba(0,0,0,.42));animation:cr-loader-logo 2.1s ease-in-out infinite}
      .coinrenta-loader-brand{margin:0;font-size:34px;line-height:1;font-weight:950;letter-spacing:-.065em}.coinrenta-loader-brand .coin{color:#f7fbfb}.coinrenta-loader-brand .renta{color:#6de0d7}.coinrenta-loader-tagline{margin:11px 0 0;color:#8da0b6;font-size:11px;letter-spacing:.10em;text-transform:uppercase;font-weight:800}
      .coinrenta-loader-track{position:relative;width:min(370px,82vw);height:6px;margin:26px auto 16px;border-radius:999px;overflow:hidden;background:rgba(255,255,255,.055);box-shadow:inset 0 0 0 1px rgba(255,255,255,.025)}.coinrenta-loader-track::before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(109,224,215,.14),transparent);animation:cr-loader-track-glow 2s linear infinite}.coinrenta-loader-track::after{content:"";position:absolute;top:0;left:-30%;width:36%;height:100%;border-radius:inherit;background:linear-gradient(90deg,transparent,#0fa7a0,#6de0d7,transparent);box-shadow:0 0 22px rgba(109,224,215,.48);animation:cr-loader-progress 1.08s ease-in-out infinite}
      .coinrenta-loader-status{display:flex;align-items:center;gap:9px;min-height:18px;color:#d4dde7;font-size:11px;font-weight:800}.coinrenta-loader-dot{width:7px;height:7px;border-radius:50%;background:#6de0d7;box-shadow:0 0 0 4px rgba(109,224,215,.08),0 0 18px rgba(109,224,215,.5);animation:cr-loader-pulse 1s ease-in-out infinite}.coinrenta-loader-meta{margin-top:9px;color:#64768d;font-size:9px;letter-spacing:.045em}
      @keyframes cr-loader-in{from{opacity:0;transform:scale(1.01)}to{opacity:1;transform:scale(1)}}@keyframes cr-loader-aurora{from{transform:scale(1) translate3d(0,0,0);opacity:.78}to{transform:scale(1.14) translate3d(2%,-1%,0);opacity:1}}@keyframes cr-loader-sheen{0%{transform:translateX(-120%)}55%,100%{transform:translateX(120%)}}@keyframes cr-loader-orbit{from{transform:rotate(0deg) scale(1)}50%{transform:rotate(180deg) scale(1.022)}to{transform:rotate(360deg) scale(1)}}@keyframes cr-loader-spin{to{transform:rotate(360deg)}}@keyframes cr-loader-spin-reverse{to{transform:rotate(-360deg)}}@keyframes cr-loader-particle{0%,100%{transform:translate3d(0,0,0) scale(.7);opacity:.25}50%{transform:translate3d(16px,-22px,0) scale(1.25);opacity:1}}@keyframes cr-loader-card{0%,100%{transform:translateY(0)}50%{transform:translateY(-5px)}}@keyframes cr-loader-glow{0%,100%{opacity:.5;transform:scale(.9)}50%{opacity:1;transform:scale(1.08)}}@keyframes cr-loader-logo{0%,100%{transform:scale(.965) rotate(-1deg)}50%{transform:scale(1.04) rotate(1deg)}}@keyframes cr-loader-track-glow{from{transform:translateX(-100%)}to{transform:translateX(100%)}}@keyframes cr-loader-progress{0%{transform:translateX(0)}100%{transform:translateX(390%)}}@keyframes cr-loader-pulse{0%,100%{transform:scale(.8);opacity:.48}50%{transform:scale(1);opacity:1}}
      @media(max-width:600px){.coinrenta-loader-card{padding:32px 20px 26px;border-radius:23px}.coinrenta-loader-brand{font-size:28px}.coinrenta-loader-logo-wrap{width:100px;height:100px}.coinrenta-loader-logo{width:76px;height:76px}.coinrenta-loader-orbit{width:94vw;height:94vw}.coinrenta-loader-particle{display:none}}@media(prefers-reduced-motion:reduce){.coinrenta-loader,.coinrenta-loader::before,.coinrenta-loader::after,.coinrenta-loader-orbit,.coinrenta-loader-orbit::before,.coinrenta-loader-orbit::after,.coinrenta-loader-particle,.coinrenta-loader-card,.coinrenta-loader-logo-wrap::before,.coinrenta-loader-ring,.coinrenta-loader-logo,.coinrenta-loader-track::before,.coinrenta-loader-track::after,.coinrenta-loader-dot{animation:none!important}}
    `}</style>
    <div className="coinrenta-loader-orbit" aria-hidden="true"/><span className="coinrenta-loader-particle a" aria-hidden="true"/><span className="coinrenta-loader-particle b" aria-hidden="true"/><span className="coinrenta-loader-particle c" aria-hidden="true"/><span className="coinrenta-loader-particle d" aria-hidden="true"/>
    <section className="coinrenta-loader-card"><div className="coinrenta-loader-logo-wrap" aria-hidden="true"><span className="coinrenta-loader-ring"/><span className="coinrenta-loader-ring two"/><Image src="/logo.webp" alt="" width={90} height={90} priority sizes="90px" className="coinrenta-loader-logo"/></div><h1 className="coinrenta-loader-brand"><span className="coin">Coin</span><span className="renta">Renta</span></h1><p className="coinrenta-loader-tagline">Tu información fiscal, bajo control</p><div className="coinrenta-loader-track" aria-hidden="true"/><div className="coinrenta-loader-status"><span className="coinrenta-loader-dot"/>{MESSAGES[messageIndex]}</div><div className="coinrenta-loader-meta">Estamos preparando CoinRenta para ti</div></section>
  </div>;
}
