import type { Metadata } from "next";
import Link from "next/link";
import LegalPage from "@/components/legal-page";

export const metadata: Metadata = { title: "Política de privacidad", description: "Información sobre el tratamiento de datos personales en CoinRenta.", robots: { index: true, follow: true } };
const P = ({ children }: { children: React.ReactNode }) => <p>{children}</p>;
const UL = ({ children }: { children: React.ReactNode }) => <ul>{children}</ul>;

export default function PrivacyPage() {
  return <LegalPage label="Privacidad y protección de datos" title="Política de privacidad" intro="Esta política explica qué datos personales puede tratar CoinRenta, para qué los utiliza, con qué base jurídica, durante cuánto tiempo y qué derechos puedes ejercer." updated="14 de septiembre de 2026" activePath="/legal/privacidad" sections={[
    { title: "1. Responsable del tratamiento", children: <><P><strong>Responsable:</strong> CoinRenta, titular del sitio web coinrenta.es.</P><P><strong>Correo de contacto en materia de privacidad:</strong> info@coinrenta.es.</P><P>La identidad jurídica completa del responsable, domicilio y demás datos exigidos por la normativa deben figurar en el Aviso legal. Si CoinRenta opera mediante una persona física o jurídica distinta del nombre comercial, prevalecerán los datos identificativos de dicha persona o entidad.</P></> },
    { title: "2. Qué datos tratamos", children: <><P>Dependiendo de las funciones que utilices, podemos tratar las siguientes categorías:</P><UL><li><strong>Datos de cuenta:</strong> correo electrónico, nombre mostrado y datos necesarios para gestionar el acceso.</li><li><strong>Datos de autenticación y seguridad:</strong> identificadores de sesión, registros técnicos y datos necesarios para detectar abusos o incidentes.</li><li><strong>Datos de cartera y operaciones:</strong> activos, saldos, movimientos, fechas, importes, comisiones, precios de adquisición/venta y otra información que decidas importar o sincronizar.</li><li><strong>Datos de conexiones externas:</strong> identificadores y credenciales o secretos técnicos necesarios para acceder a las APIs de los servicios que conectes. CoinRenta debe utilizar, cuando el proveedor lo permita, permisos mínimos y sin capacidad de retirar fondos.</li><li><strong>Datos de soporte y comunicaciones:</strong> contenido de mensajes o solicitudes que nos envíes y datos necesarios para responderlas.</li><li><strong>Datos contractuales y de facturación:</strong> información necesaria para gestionar una suscripción de pago y las obligaciones contables o fiscales asociadas.</li><li><strong>Datos de medición y analítica:</strong> información obtenida mediante Google Analytics únicamente cuando hayas otorgado el consentimiento correspondiente.</li></UL><P>No solicitamos datos que no sean necesarios para las finalidades descritas. No introduzcas en CoinRenta categorías especiales de datos personales ni información de terceros que no estés legitimado para aportar.</P></> },
    { title: "3. Finalidades del tratamiento", children: <UL><li>Crear y administrar tu cuenta y autenticarte.</li><li>Prestar las funciones de importación, organización, conciliación, consulta y análisis de información sobre activos digitales que solicites.</li><li>Generar resúmenes, cálculos y documentación informativa relacionada con la fiscalidad de criptoactivos.</li><li>Gestionar conexiones con exchanges y otras fuentes que autorices.</li><li>Proteger la seguridad del servicio, prevenir fraude, abuso y accesos no autorizados, y resolver incidencias.</li><li>Atender solicitudes de soporte y comunicaciones relacionadas con el servicio.</li><li>Gestionar contratación, facturación y cobros de la suscripción Premium.</li><li>Obtener estadísticas de uso mediante Google Analytics cuando exista consentimiento.</li><li>Cumplir obligaciones legales aplicables y atender requerimientos de autoridades competentes.</li></UL> },
    { title: "4. Bases jurídicas", children: <><P>El tratamiento se realizará, según el caso, sobre las siguientes bases del artículo 6 del RGPD:</P><UL><li><strong>Ejecución de un contrato o aplicación de medidas precontractuales:</strong> para crear la cuenta, prestar el servicio y gestionar una suscripción.</li><li><strong>Consentimiento:</strong> para cookies y tecnologías analíticas no estrictamente necesarias y otras finalidades que requieran autorización.</li><li><strong>Obligación legal:</strong> para cumplir obligaciones fiscales, contables, mercantiles, de seguridad o requerimientos legítimos de autoridades.</li><li><strong>Interés legítimo:</strong> para mantener y proteger el servicio, prevenir abusos y gestionar reclamaciones, aplicando ponderación y respetando tus derechos.</li></UL><P>Cuando un tratamiento se base en consentimiento, puedes retirarlo en cualquier momento sin que la retirada afecte a la licitud del tratamiento realizado previamente.</P></> },
    { title: "5. Proveedores y destinatarios", children: <><P>Podemos utilizar proveedores tecnológicos que actúen como encargados del tratamiento. Entre los servicios utilizados o previstos para CoinRenta se incluyen <strong>Supabase</strong> para autenticación/base de datos, <strong>Vercel</strong> para infraestructura y alojamiento, <strong>Google Analytics</strong> para analítica cuando exista consentimiento y <strong>Stripe</strong> para la gestión del pago de las suscripciones Premium.</P><P>Stripe podrá recibir los datos necesarios para procesar el pago y prevenir fraude. CoinRenta no almacena los datos completos de tarjetas cuando el proceso de pago sea gestionado por Stripe.</P><P>No vendemos tus datos personales ni los cedemos a terceros para sus propias finalidades publicitarias. Solo comunicaremos información a autoridades, asesores, proveedores o terceros cuando exista una base jurídica para ello y en la medida necesaria.</P></> },
    { title: "6. Transferencias internacionales", children: <><P>Dependiendo de la infraestructura y de los proveedores utilizados, determinados datos pueden ser tratados desde países situados fuera del Espacio Económico Europeo. Cuando exista una transferencia internacional, se aplicarán los mecanismos previstos en el capítulo V del RGPD, como una decisión de adecuación, cláusulas contractuales tipo u otra garantía legalmente válida.</P><P>En particular, Google, Stripe, Supabase o Vercel pueden disponer de infraestructura internacional. La información actualizada sobre proveedores, ubicaciones y garantías aplicables podrá consultarse mediante solicitud a info@coinrenta.es.</P></> },
    { title: "7. Conservación de los datos", children: <><P>Conservamos los datos durante el tiempo necesario para cumplir la finalidad para la que se obtuvieron. Mientras mantengas tu cuenta, conservaremos los datos necesarios para prestarte el servicio.</P><P>Los datos asociados a una suscripción podrán conservarse durante los plazos necesarios para gestionar la relación contractual, facturación y obligaciones legales. Tras la cancelación, determinados datos podrán conservarse bloqueados durante los plazos legalmente exigibles.</P></> },
    { title: "8. Derechos", children: <><P>Puedes ejercer los derechos de <strong>acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad</strong>, así como retirar el consentimiento cuando esa sea la base jurídica.</P><P>Puedes solicitarlo en <strong>info@coinrenta.es</strong>, indicando el derecho que deseas ejercer y aportando información suficiente para verificar tu identidad cuando sea necesario.</P><P>También tienes derecho a presentar una reclamación ante la <Link href="https://www.aepd.es/" target="_blank" rel="noreferrer">Agencia Española de Protección de Datos (AEPD)</Link> u otra autoridad de control competente.</P></> },
    { title: "9. Decisiones automatizadas y elaboración de perfiles", children: <P>CoinRenta no pretende adoptar decisiones automatizadas con efectos jurídicos o efectos significativamente similares sobre ti. Las funciones de análisis y cálculo tienen finalidad informativa y de organización y no sustituyen la valoración profesional de tus obligaciones fiscales.</P> },
    { title: "10. Seguridad", children: <><P>Aplicamos medidas técnicas y organizativas razonables para proteger la información frente a acceso no autorizado, pérdida, alteración, divulgación o destrucción.</P><P>Cuando conectes un exchange, utiliza siempre permisos mínimos y nunca proporciones claves con permisos de retirada o transferencia de fondos.</P></> },
    { title: "11. Datos aportados desde exchanges y CSV", children: <><P>Los datos que importes desde CSV o que obtengamos mediante una conexión autorizada se utilizan para las funciones que hayas solicitado. Tú eres responsable de disponer de base jurídica para aportar información correspondiente a terceros y de revisar que los datos importados sean correctos.</P><P>CoinRenta no adquiere la titularidad de tus activos digitales ni custodia fondos por el mero hecho de que organice información sobre ellos.</P></> },
    { title: "12. Actualizaciones de esta política", children: <P>Podremos actualizar esta política cuando cambien el servicio, los proveedores utilizados o la normativa aplicable. La versión publicada en esta página será la vigente.</P> },
  ]} />;
}
