import { createHash } from "node:crypto";

export type CsvRow = Record<string, string>;
export type NormalizedMovement = {
  externalId: string;
  occurredAt: string;
  transactionType: string;
  originalType: string;
  direction: "incoming" | "outgoing" | "neutral";
  baseAsset: string | null;
  baseAmount: number | null;
  quoteAsset: string | null;
  quoteAmount: number | null;
  feeAsset: string | null;
  feeAmount: number | null;
  price: number | null;
  priceCurrency: string | null;
  classification: "classified" | "needs_review";
  raw: { sourceFile: string; sourceExchange: string; row: CsvRow; parser: string };
};

export const CSV_SUPPORTED_EXCHANGES = new Set(["bitpanda", "binance", "coinbase", "kraken", "crypto.com", "cryptocom", "kucoin", "bybit", "okx"]);
const FIAT = new Set(["EUR", "USD", "GBP", "CHF", "PLN", "SEK", "DKK", "NOK", "AUD", "CAD", "JPY", "SGD"]);
const QUOTES = ["USDT", "USDC", "FDUSD", "BUSD", "TUSD", "DAI", "EUR", "USD", "GBP", "TRY", "BRL", "AUD", "CAD", "JPY", "CHF", "BTC", "ETH", "BNB"];

const clean = (value: unknown) => String(value ?? "").replace(/^\uFEFF/, "").trim();
const headerKey = (value: string) => clean(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "");
function asNumber(value: unknown) { let raw = clean(value).replace(/\s/g, "").replace(/[^0-9,().+\-]/g, ""); if (!raw || raw === "-") return null; const negative = /^\(.*\)$/.test(raw); raw = raw.replace(/[()]/g, ""); if (raw.includes(",") && raw.includes(".")) raw = raw.lastIndexOf(",") > raw.lastIndexOf(".") ? raw.replace(/\./g, "").replace(",", ".") : raw.replace(/,/g, ""); else if (raw.includes(",")) { const decimals = raw.length - raw.lastIndexOf(",") - 1; raw = decimals === 3 && raw.indexOf(",") > 0 ? raw.replace(/,/g, "") : raw.replace(",", "."); } const result = Number(raw); if (!Number.isFinite(result)) return null; return negative ? -Math.abs(result) : result; }
function asAsset(value: unknown) { const result = clean(value).toUpperCase().replace(/\s+/g, ""); return result || null; }
function asDate(value: unknown) { const raw = clean(value); if (!raw) return null; const n = Number(raw); if (Number.isFinite(n) && raw.length >= 10) { const date = new Date(n < 2000000000 ? n * 1000 : n); if (Number.isFinite(date.getTime())) return date.toISOString(); } const date = new Date(raw); return Number.isFinite(date.getTime()) ? date.toISOString() : null; }
function parseLine(line: string, delimiter: string) { const out: string[] = []; let cell = ""; let quoted = false; for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"') { if (quoted && line[index + 1] === '"') { cell += '"'; index += 1; } else quoted = !quoted; } else if (char === delimiter && !quoted) { out.push(cell); cell = ""; } else cell += char; } out.push(cell); return out; }
function readRows(text: string) { const lines = text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n"); const nonEmpty = lines.map((line, index) => ({ line, index })).filter((item) => item.line.trim()); if (!nonEmpty.length) throw new Error("El archivo está vacío."); const headerInfo = nonEmpty.find((item) => { const key = headerKey(item.line); return key.includes("transactionid") || key.includes("userid") || key.includes("utctime") || key.includes("timestamp") || key.includes("transactiontype") || key.includes("businesstype") || key.includes("ordertype") || key.includes("subtype") || key.includes("transtype") || key.includes("biztype"); }) || nonEmpty[0]; const delimiter = headerInfo.line.includes(";") ? ";" : headerInfo.line.includes("\t") ? "\t" : ","; const headers = parseLine(headerInfo.line, delimiter).map(clean); if (headers.length < 2) throw new Error("No se ha podido identificar la cabecera del archivo."); const rows: CsvRow[] = []; for (let index = headerInfo.index + 1; index < lines.length; index += 1) { if (!lines[index].trim()) continue; const cells = parseLine(lines[index], delimiter); const row: CsvRow = {}; headers.forEach((header, column) => { row[header] = clean(cells[column]); }); if (Object.values(row).some(Boolean)) rows.push(row); } return rows; }
function rowMap(row: CsvRow) { const values = new Map(Object.entries(row).map(([key, value]) => [headerKey(key), clean(value)])); return (...names: string[]) => { for (const name of names) { const value = values.get(headerKey(name)); if (value !== undefined && value !== "") return value; } return ""; }; }
function pairAssets(pair: string, base: string, quote: string) { const explicitBase = asAsset(base); const explicitQuote = asAsset(quote); if (explicitBase && explicitQuote) return { base: explicitBase, quote: explicitQuote }; const normalized = clean(pair).replace(/[\s_\/-]/g, "").toUpperCase(); const candidate = QUOTES.find((quoteAsset) => normalized.endsWith(quoteAsset) && normalized.length > quoteAsset.length); return candidate ? { base: normalized.slice(0, -candidate.length), quote: candidate } : { base: explicitBase, quote: explicitQuote }; }
function classify(type: string, direction = "", description = "") { const value = `${type} ${description}`.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[-\s]+/g, "_"); const flow = direction.toLowerCase(); if (/buy|purchase|bought|compra|comprado|comprada/.test(value)) return "buy"; if (/sell|sold|venta|vendido|vendida/.test(value)) return "sell"; if (/convert|conversion|swap|convertir/.test(value)) return "trade"; if (/withdraw|cash_out|removal|entnahme|retirada|withdrawal/.test(value)) return "withdrawal"; if (/deposit|receive|received|cash_in|deposito|entrada/.test(value)) return "deposit"; if (/transfer/.test(value)) return flow.includes("out") ? "transfer_out" : flow.includes("in") ? "transfer_in" : "transfer"; if (/staking|stake|earn|allocation|deallocation/.test(value)) return "staking"; if (/reward|bonus|referral|airdrop|fork/.test(value)) return "reward"; if (/interest|yield|interes|interés/.test(value)) return "interest"; if (/cashback/.test(value)) return "cashback"; if (/fee|commission|comision|comisión|fees/.test(value)) return "fee"; if (/dividend|dividendo|income/.test(value)) return "income"; if (/refund|reversal|reembolso/.test(value)) return "income"; if (/card.*payment|payment.*card|pago.*tarjeta|spend/.test(value)) return "expense"; if (/out|debit|salida/.test(flow) || flow === "-") return "withdrawal"; if (/in|credit|entrada/.test(flow) || flow === "+") return "deposit"; return "other"; }
function signed(value: number | null, type: string, direction: string) { if (value === null) return null; if (["buy", "deposit", "transfer_in", "reward", "staking", "airdrop", "interest", "cashback", "income"].includes(type)) return Math.abs(value); if (["sell", "withdrawal", "transfer_out", "fee", "expense"].includes(type)) return -Math.abs(value); if (/out|debit|salida/.test(direction.toLowerCase())) return -Math.abs(value); if (/in|credit|entrada/.test(direction.toLowerCase())) return Math.abs(value); return value; }
function signedChange(value: number | null) { return value === null || !Number.isFinite(value) ? null : value; }
function movementDirection(amount: number | null, direction: string) { const flow = direction.toLowerCase(); if (/out|debit|salida/.test(flow) || (amount !== null && amount < 0)) return "outgoing" as const; if (/in|credit|entrada/.test(flow) || (amount !== null && amount > 0)) return "incoming" as const; return "neutral" as const; }
function stableId(exchange: string, parser: string, row: CsvRow, preferred: string) { const id = clean(preferred); if (id) return `${exchange}:${id}`; const canonical = Object.entries(row).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `${headerKey(key)}=${clean(value)}`).join("|"); return `${exchange}:row:${createHash("sha256").update(`${parser}|${canonical}`).digest("hex").slice(0, 40)}`; }

type MovementInput = { occurredAt: string; transactionType: string; originalType: string; direction: string; baseAsset: string | null; baseAmount: number | null; quoteAsset: string | null; quoteAmount: number | null; feeAsset: string | null; feeAmount: number | null; price: number | null; priceCurrency: string | null };
function make(exchange: string, parser: string, row: CsvRow, input: MovementInput): NormalizedMovement { const { direction: rawDirection, ...movement } = input; return { ...movement, externalId: stableId(exchange, parser, row, ""), direction: movementDirection(input.baseAmount, rawDirection), classification: input.transactionType === "other" ? "needs_review" : "classified", raw: { sourceFile: "", sourceExchange: exchange, row, parser } }; }

function bitpanda(rows: CsvRow[], file: string) { return rows.map((row) => { const get = rowMap(row); const original = get("Transaction Type", "Type", "Operation Type") || "unknown"; const direction = get("In/Out", "Direction"); const type = classify(original, direction); const asset = asAsset(get("Asset", "Cryptocurrency")); const fiat = asAsset(get("Fiat", "Currency")) || "EUR"; const assetAmount = asNumber(get("Amount Asset", "Asset Amount", "Shares", "Quantity")); const fiatAmount = asNumber(get("Amount Fiat", "Fiat Amount", "Total", "Amount EUR")); const fee = asNumber(get("Fee", "Fees", "Fee Amount")); const feeAsset = asAsset(get("Fee asset", "Fee Asset", "Fee Currency")); const price = asNumber(get("Asset market price", "Asset Market Price", "Price", "Rate")); const priceCurrency = asAsset(get("Asset market price currency", "Asset Market Price Currency", "Price Currency")) || fiat; const trade = type === "buy" || type === "sell"; const baseAsset = trade ? asset : assetAmount !== null && asset ? asset : fiat; const baseAmount = trade ? (assetAmount === null ? null : type === "buy" ? Math.abs(assetAmount) : -Math.abs(assetAmount)) : assetAmount !== null && asset ? signed(assetAmount, type, direction) : signed(fiatAmount, type, direction); const quoteAmount = trade && fiatAmount !== null ? (type === "buy" ? -Math.abs(fiatAmount) : Math.abs(fiatAmount)) : null; const parser = "bitpanda-history"; const movement = make("bitpanda", parser, row, { occurredAt: asDate(get("Timestamp", "Date", "Time")) || "", transactionType: type, originalType: original, direction, baseAsset, baseAmount, quoteAsset: trade ? fiat : null, quoteAmount, feeAsset, feeAmount: fee === null ? null : -Math.abs(fee), price, priceCurrency }); movement.externalId = stableId("bitpanda", parser, row, get("Transaction ID", "TransactionID", "PID", "ID")); movement.raw.sourceFile = file; return movement; }); }

function binance(rows: CsvRow[], file: string) { return rows.map((row) => { const get = rowMap(row); const utc = get("UTC_Time", "UTC Time", "Date(UTC)", "Date", "Time", "Timestamp", "Create Time"); const operation = get("Operation", "Transaction Type", "Type", "Activity"); const description = get("Remark", "Transaction Description", "Description", "Notes"); const pair = get("Pair", "Market", "Symbol", "Trading Pair"); const side = get("Side"); const assets = pairAssets(pair, get("Base Asset", "Base Coin"), get("Quote Asset", "Quote Coin")); const coin = asAsset(get("Coin", "Asset", "Currency")); const change = asNumber(get("Change", "Net Change", "Balance Change")); const amount = asNumber(get("Amount", "Executed", "Executed Quantity", "Quantity", "Volume")); const total = asNumber(get("Total", "Quote Amount", "Cost", "Funds")); const rawType = operation || side || "unknown"; const type = pair && side ? (side.toLowerCase() === "sell" ? "sell" : "buy") : classify(rawType, get("Direction", "Cash Flow", "In/Out"), description); const fee = asNumber(get("Fee", "Commission", "Transaction Fee")); const feeAsset = asAsset(get("Fee Coin", "Fee Currency", "Commission Asset")); const price = asNumber(get("Price", "Average Price", "Execution Price")); let baseAsset = coin || assets.base; let baseAmount: number | null = null; let quoteAsset: string | null = null; let quoteAmount: number | null = null; if (change !== null && !pair) baseAmount = signedChange(change); else if (pair && amount !== null && total !== null && (type === "buy" || type === "sell")) { baseAsset = assets.base; baseAmount = type === "buy" ? Math.abs(amount) : -Math.abs(amount); quoteAsset = assets.quote; quoteAmount = type === "buy" ? -Math.abs(total) : Math.abs(total); } else baseAmount = signed(amount, type, get("Direction", "Cash Flow", "In/Out")); const parser = pair ? "binance-trades" : "binance-account-log"; const movement = make("binance", parser, row, { occurredAt: asDate(utc) || "", transactionType: type, originalType: rawType, direction: get("Direction", "Cash Flow", "In/Out"), baseAsset, baseAmount, quoteAsset, quoteAmount, feeAsset, feeAmount: fee === null ? null : -Math.abs(fee), price, priceCurrency: asAsset(get("Price Currency", "Quote Currency", "Currency")) || assets.quote }); movement.externalId = stableId("binance", parser, row, get("Transaction ID", "TransactionID", "TXID", "TxID", "Trade ID", "TradeId", "Order ID", "OrderId", "ID", "Hash")); movement.raw.sourceFile = file; return movement; }); }

function coinbase(rows: CsvRow[], file: string) { return rows.map((row) => { const get = rowMap(row); const original = get("Transaction Type", "Type", "Transaction", "Activity") || "unknown"; const description = get("Notes", "Note", "Description", "Details"); const direction = get("Direction", "Flow"); const type = classify(original, direction, description); const asset = asAsset(get("Asset", "Currency", "Asset Symbol")); const qty = asNumber(get("Quantity Transacted", "Quantity", "Amount", "Asset Amount")); const subtotal = asNumber(get("Subtotal", "Subtotal (USD)", "Subtotal (EUR)")); const total = asNumber(get("Total (inclusive of fees and/or spread)", "Total", "Total (USD)", "Total (EUR)")); const fee = asNumber(get("Fees and/or Spread", "Fees", "Fee")); const price = asNumber(get("Price at Transaction", "Price", "Spot Price")); const priceCurrency = asAsset(get("Price Currency", "Currency")) || "USD"; const cash = total ?? subtotal; const isTrade = type === "buy" || type === "sell"; const movement = make("coinbase", "coinbase-statement", row, { occurredAt: asDate(get("Timestamp", "Date", "Created At", "Time")) || "", transactionType: type, originalType: original, direction, baseAsset: asset, baseAmount: signed(qty, type, direction), quoteAsset: isTrade && qty !== null ? priceCurrency : null, quoteAmount: isTrade && qty !== null && cash !== null ? (type === "buy" ? -Math.abs(cash) : Math.abs(cash)) : null, feeAsset: fee !== null ? priceCurrency : null, feeAmount: fee === null ? null : -Math.abs(fee), price, priceCurrency }); movement.externalId = stableId("coinbase", "coinbase-statement", row, get("Transaction ID", "ID", "Reference", "Hash")); movement.raw.sourceFile = file; return movement; }); }

function kraken(rows: CsvRow[], file: string) { return rows.map((row) => { const get = rowMap(row); const original = get("Type", "Transaction Type", "Transaction") || "unknown"; const subtype = get("Subtype", "Sub Type"); const pair = pairAssets(get("Pair", "Symbol", "Market"), get("Base Asset"), get("Quote Asset")); const side = get("Side", "type").toLowerCase(); const amount = asNumber(get("Amount", "Vol", "Volume", "Quantity")); const cost = asNumber(get("Cost", "Total", "Funds")); const fee = asNumber(get("Fee", "Fees")); const asset = asAsset(get("Asset", "Currency")) || pair.base; const direction = get("Direction", "Flow"); const isTrade = original.toLowerCase() === "trade" && Boolean(pair.base && pair.quote); const type = isTrade ? (side === "sell" ? "sell" : "buy") : classify(original, direction, subtype); let baseAsset = asset; let baseAmount: number | null; let quoteAsset: string | null = null; let quoteAmount: number | null = null; if (!isTrade && get("Amount", "Vol", "Volume", "Quantity")) baseAmount = signedChange(amount); else if (isTrade && amount !== null && cost !== null) { baseAsset = pair.base; baseAmount = side === "sell" ? -Math.abs(amount) : Math.abs(amount); quoteAsset = pair.quote; quoteAmount = side === "sell" ? Math.abs(cost) : -Math.abs(cost); } else baseAmount = signed(amount, type, direction); const parser = isTrade ? "kraken-trades" : "kraken-ledger"; const movement = make("kraken", parser, row, { occurredAt: asDate(get("Time", "Timestamp", "Date")) || "", transactionType: type, originalType: subtype ? `${original} / ${subtype}` : original, direction, baseAsset, baseAmount, quoteAsset, quoteAmount, feeAsset: fee !== null ? asset : null, feeAmount: fee === null ? null : -Math.abs(fee), price: asNumber(get("Price", "Rate")), priceCurrency: pair.quote }); movement.externalId = stableId("kraken", parser, row, get("Txid", "TXID", "Transaction ID", "Refid", "Reference ID", "Ordertxid", "Trade ID", "ID")); movement.raw.sourceFile = file; return movement; }); }

function cryptoCom(rows: CsvRow[], file: string) { return rows.map((row) => { const get = rowMap(row); const original = get("Transaction Type", "Type", "Transaction", "Activity", "Biz Type", "Business Type") || "unknown"; const direction = get("Direction", "In/Out", "Flow", "Side"); const description = get("Description", "Notes", "Remark", "Details"); const type = classify(original, direction, description); const asset = asAsset(get("Currency", "Coin", "Asset", "Crypto Currency")); const change = asNumber(get("Change", "Balance Change", "Amount", "Quantity", "Net Amount")); const balance = get("Balance", "Wallet Balance", "Available Balance"); const fee = asNumber(get("Fee", "Fees", "Transaction Fee")); const feeAsset = asAsset(get("Fee Currency", "Fee Coin", "Fee Asset")); const pair = pairAssets(get("Pair", "Symbol", "Instrument"), get("Base Asset"), get("Quote Asset")); const price = asNumber(get("Price", "Execution Price", "Average Price")); const total = asNumber(get("Total", "Cost", "Quote Amount")); const isTrade = (type === "buy" || type === "sell") && Boolean(pair.base && pair.quote); const amount = asNumber(get("Executed Quantity", "Quantity", "Volume", "Amount")); let baseAsset = asset || pair.base; let baseAmount = change !== null ? signedChange(change) : signed(amount, type, direction); let quoteAsset: string | null = null; let quoteAmount: number | null = null; if (isTrade && amount !== null && total !== null) { baseAsset = pair.base; baseAmount = type === "buy" ? Math.abs(amount) : -Math.abs(amount); quoteAsset = pair.quote; quoteAmount = type === "buy" ? -Math.abs(total) : Math.abs(total); } const parser = balance ? "crypto-com-wallet-ledger" : isTrade ? "crypto-com-trades" : "crypto-com-wallet"; const movement = make("crypto.com", parser, row, { occurredAt: asDate(get("Timestamp", "Date", "Time", "Created At")) || "", transactionType: type, originalType: original, direction, baseAsset, baseAmount, quoteAsset, quoteAmount, feeAsset, feeAmount: fee === null ? null : -Math.abs(fee), price, priceCurrency: asAsset(get("Price Currency", "Quote Currency")) || pair.quote }); movement.externalId = stableId("crypto.com", parser, row, get("Transaction ID", "Transaction Id", "ID", "Reference", "Trade ID", "Order ID", "Hash")); movement.raw.sourceFile = file; return movement; }); }

function kucoin(rows: CsvRow[], file: string) { return rows.map((row) => { const get = rowMap(row); const original = get("BizType", "Biz Type", "Business Type", "Transaction Type", "Type", "Activity") || "unknown"; const direction = get("Direction", "Flow", "Side", "In/Out"); const pair = pairAssets(get("Symbol", "Pair", "Market"), get("Base Coin", "Base Asset"), get("Quote Coin", "Quote Asset")); const asset = asAsset(get("Currency", "Coin", "Asset")) || pair.base; const amount = asNumber(get("Amount", "Change", "Balance Change", "Quantity")); const balance = get("Balance", "Available Balance", "Wallet Balance"); const total = asNumber(get("Total", "Cost", "Funds", "Quote Amount")); const price = asNumber(get("Price", "Filled Price", "Average Price")); const fee = asNumber(get("Fee", "Fees", "Transaction Fee")); const feeAsset = asAsset(get("Fee Currency", "Fee Coin", "Fee Asset")); const type = classify(original, direction); const isTrade = (type === "buy" || type === "sell") && Boolean(pair.base && pair.quote) && total !== null; const movement = make("kucoin", balance ? "kucoin-account-ledger" : isTrade ? "kucoin-trades" : "kucoin-ledger", row, { occurredAt: asDate(get("Time", "Timestamp", "Date", "Created At")) || "", transactionType: type, originalType: original, direction, baseAsset: isTrade ? pair.base : asset, baseAmount: isTrade && amount !== null ? (type === "buy" ? Math.abs(amount) : -Math.abs(amount)) : signed(amount, type, direction), quoteAsset: isTrade ? pair.quote : null, quoteAmount: isTrade ? (type === "buy" ? -Math.abs(total as number) : Math.abs(total as number)) : null, feeAsset, feeAmount: fee === null ? null : -Math.abs(fee), price, priceCurrency: asAsset(get("Price Currency", "Quote Currency")) || pair.quote }); movement.externalId = stableId("kucoin", movement.raw.parser, row, get("Trade ID", "TradeId", "Order ID", "OrderId", "Transaction ID", "ID", "Hash", "Reference")); movement.raw.sourceFile = file; return movement; }); }

function bybit(rows: CsvRow[], file: string) { return rows.map((row) => { const get = rowMap(row); const original = get("Type", "Transaction Type", "Activity") || "unknown"; const direction = get("Direction", "Side", "Cash Flow"); const category = get("Category", "Product Category"); const asset = asAsset(get("Currency", "Coin", "Asset")); const change = asNumber(get("Change", "Change Amount", "Balance Change")); const cashFlow = asNumber(get("Cash Flow", "Cashflow")); const cashBalance = asNumber(get("Cash Balance", "CashBalance", "Balance", "Wallet Balance")); const qty = asNumber(get("Qty", "Quantity", "Amount", "Size")); const price = asNumber(get("Trade Price", "Price", "Filled Price")); const fee = asNumber(get("Fee", "Fees", "Transaction Fee")); const feeAsset = asAsset(get("Fee Coin", "Fee Currency", "Fee Asset")); const type = classify(original, direction, category); const baseAmount = change !== null ? signedChange(change) : cashFlow !== null && cashFlow !== 0 ? signedChange(cashFlow) : signed(qty, type, direction); const movement = make("bybit", "bybit-transaction-log", row, { occurredAt: asDate(get("Transaction Time", "UTC Time", "Timestamp", "Date", "Time")) || "", transactionType: type, originalType: original, direction, baseAsset: asset, baseAmount, quoteAsset: null, quoteAmount: null, feeAsset, feeAmount: fee === null ? null : -Math.abs(fee), price, priceCurrency: asAsset(get("Price Currency", "Quote Currency")) }); movement.externalId = stableId("bybit", "bybit-transaction-log", row, get("Transaction ID", "TransactionId", "Trade ID", "TradeId", "Order ID", "OrderId", "ID", "UID")); movement.raw.sourceFile = file; if (cashBalance !== null) movement.raw.row["__coinrenta_reported_balance"] = String(cashBalance); if (asset) movement.raw.row["__coinrenta_reported_balance_asset"] = asset; return movement; }); }

function okx(rows: CsvRow[], file: string) { return rows.map((row) => { const get = rowMap(row); const original = get("Trade Type", "Transaction Type", "Type", "Activity") || "unknown"; const action = get("Action", "Side", "Direction"); const asset = asAsset(get("Balance Unit", "Currency", "Asset", "Fee Unit")); const balanceChange = asNumber(get("Balance Change", "Change", "Cash Flow")); const balance = asNumber(get("Balance", "Position Balance", "Wallet Balance")); const amount = asNumber(get("Amount", "Quantity", "Size")); const price = asNumber(get("Filled Price", "Price", "Average Price")); const fee = asNumber(get("Fee", "Fees")); const feeAsset = asAsset(get("Fee Unit", "Fee Currency", "Fee Asset")); const type = classify(original, action); const movement = make("okx", "okx-trading-history", row, { occurredAt: asDate(get("Time", "Timestamp", "Date")) || "", transactionType: type, originalType: original, direction: action, baseAsset: asset, baseAmount: balanceChange !== null ? signedChange(balanceChange) : signed(amount, type, action), quoteAsset: null, quoteAmount: null, feeAsset, feeAmount: fee === null ? null : -Math.abs(fee), price, priceCurrency: asAsset(get("Price Unit", "Price Currency", "Quote Currency")) }); movement.externalId = stableId("okx", "okx-trading-history", row, get("Trade ID", "TradeId", "Order ID", "OrderId", "Transaction ID", "ID")); movement.raw.sourceFile = file; if (balance !== null) movement.raw.row["__coinrenta_reported_balance"] = String(balance); if (asset) movement.raw.row["__coinrenta_reported_balance_asset"] = asset; return movement; }); }

export function normalizeExchangeCsv(exchange: string, rows: CsvRow[], fileName = "") { const code = exchange.trim().toLowerCase(); const movements = code === "bitpanda" ? bitpanda(rows, fileName) : code === "binance" ? binance(rows, fileName) : code === "coinbase" ? coinbase(rows, fileName) : code === "kraken" ? kraken(rows, fileName) : code === "crypto.com" || code === "cryptocom" ? cryptoCom(rows, fileName) : code === "kucoin" ? kucoin(rows, fileName) : code === "bybit" ? bybit(rows, fileName) : code === "okx" ? okx(rows, fileName) : (() => { throw new Error(`Exchange no soportado: ${exchange}`); })(); return movements.map((movement) => ({ ...movement, raw: { ...movement.raw, sourceFile: fileName, sourceExchange: code } })); }
function parseText(text: string) { return readRows(text); }
export function decodeExchangeCsv(buffer: ArrayBuffer) { const bytes = new Uint8Array(buffer); if (bytes[0] === 0xff && bytes[1] === 0xfe) return parseText(new TextDecoder("utf-16le").decode(bytes.slice(2))); if (bytes[0] === 0xfe && bytes[1] === 0xff) return parseText(new TextDecoder("utf-16be").decode(bytes.slice(2))); const utf8 = new TextDecoder("utf-8").decode(bytes); const text = (utf8.match(/�/g) || []).length > 2 ? new TextDecoder("windows-1252").decode(bytes) : utf8; return parseText(text); }
