import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import LogoutButton from "@/components/logout-button";
import CoinRentaLogo from "@/components/coinrenta-logo";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "Resumen", description: "Resumen patrimonial y fiscal de CoinRenta.", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
const nav = [["▦","Resumen","/dashboard"],["↔","Exchanges","/dashboard/exchanges"],["⇧","Importar CSV","/dashboard/importar"],["≋","Movimientos","/dashboard/movimientos"],["€","Fiscalidad","/dashboard/fiscalidad"],["▣","Informes","/dashboard/informes"]];

export default async function DashboardPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
 const [{data:profile},{count:transactionCount},{count:importCount},{data:snapshots},{data:transactions}]=await Promise.all([
  supabase.from("profiles").select("display_name,role").eq("id",user.id).maybeSingle(),
  supabase.from("transactions").select("id",{count:"exact",head:true}).eq("user_id",user.id),
  supabase.from("imports").select("id",{count:"exact",head:true}).eq("user_id",user.id),
  supabase.from("balance_snapshots").select("captured_at,value_eur,quantity,asset:assets(symbol,name),account:accounts(name,connection:exchange_connections(label,exchange:exchanges(name,code)))").eq("user_id",user.id).order("captured_at",{ascending:true}).limit(1000),
  supabase.from("transactions").select("id,occurred_at,transaction_type,base_amount,quote_amount,price_currency,accounts(name),assets:assets(symbol)").eq("user_id",user.id).order("occurred_at",{ascending:false}).limit(5)
 ]);
 const role=profile?.role||"free"; const plan=role==="admin"?"Admin":role==="pro"?"Pro":"Free"; const hasPro=role!=="free";
 const latest=new Map<string,any>(); for(const row of snapshots||[]){const account=Array.isArray(row.account)?row.account[0]:row.account;const asset=Array.isArray(row.asset)?row.asset[0]:row.asset;const key=`${account?.name||"cuenta"}:${asset?.symbol||"asset"}`;if(!latest.has(key)||new Date(row.captured_at).getTime()>new Date(latest.get(key).captured_at).getTime())latest.set(key,{...row,account,asset})}
 const exchanges=new Map<string,{name:string;code:string;value:number;assets:number}>(); for(const item of latest.values()){const ex=item.account?.connection?.exchange;const key=ex?.code||ex?.name||"other";const cur=exchanges.get(key)||{name:ex?.name||"Sin exchange",code:ex?.code||"—",value:0,assets:0};cur.value+=Number(item.value_eur||0);cur.assets+=1;exchanges.set(key,cur)}
 const exchangeRows=[...exchanges.values()].sort((a,b)=>b.value-a.value); const total=exchangeRows.reduce((s,x)=>s+x.value,0); const chart=makeChart(snapshots||[]); const name=profile?.display_name||user.email?.split("@")[0]||"usuario"; const initials=name.slice(0,1).toUpperCase(); const year=new Date().getFullYear();
 return <div className="app-shell dashboard-pro-shell" style={{display:"block"}}><aside className="app-sidebar"><CoinRentaLogo/><nav className="app-nav" aria-label="Panel principal">{nav.map(([icon,label,href],i)=><Link className={`app-nav-item ${i===0?"active":""}`} href={href} key={href}><span>{icon}</span>{label}</Link>)}<Link className="app-nav-item" href="/dashboard/ayuda"><span>?</span>Ayuda</Link><Link className="app-nav-item" href="/dashboard/configuracion"><span>⚙</span>Configuración</Link>{role==="admin"&&<Link className="app-nav-item admin-nav" href="/dashboard/usuarios"><span>♙</span>Usuarios</Link>}</nav><div className="sidebar-pro-card"><div className="pro-card-title"><span className="pro-crown">♛</span><strong>Plan {plan}</strong><span className="plan-active">Activo</span></div><p>{hasPro?"Acceso completo a las funcionalidades.":"Funciones esenciales. Pásate a Pro para desbloquear informes y automatizaciones."}</p><Link className="btn btn-outline-full" href="/dashboard/configuracion">{hasPro?"Gestionar suscripción":"Ver Plan Pro"}</Link></div><div className="sidebar-bottom"><LogoutButton/></div></aside>
 <main className="app-main"><header className="app-topbar dashboard-topbar-modern"><div className="dashboard-search">⌕ <span>Buscar por activo, exchange, transacción...</span></div><div className="topbar-actions"><span className="notification">♧<i/></span><span className="profile-chip">{initials}</span><div className="profile-summary"><strong>{name}</strong><span>{plan}</span></div><span className="profile-chevron">⌄</span></div></header><section className="dashboard-content dashboard-modern-content"><div className="dashboard-heading-row"><div><h1>Hola, {name} 👋</h1><p>Aquí tienes un resumen de tu actividad fiscal y patrimonial.</p></div><button className="period-selector" type="button">▣ &nbsp;Ejercicio fiscal {year}　⌄</button></div>
 <div className="dashboard-layout-grid"><div className="dashboard-main-column"><div className="stat-grid stat-grid-modern"><Stat icon="◎" label="Total de activos" value={eur(total)} note="Tu patrimonio actual"/><Stat icon="▤" label="Movimientos" value={String(transactionCount||0)} note="Movimientos registrados"/><Stat icon="⇧" label="Importaciones" value={String(importCount||0)} note="Archivos importados"/><Stat icon="✓" label="Activos" value={String(latest.size)} note="Posiciones detectadas"/></div>
 <section className="panel-card chart-card"><div className="panel-head"><h3>Evolución de tus activos</h3><div className="chart-periods"><span>7D</span><span>30D</span><span>3M</span><span className="selected">1A</span><span>Todo</span></div></div><div className="asset-chart"><div className="chart-y-labels"><span>€ 35.000</span><span>€ 28.000</span><span>€ 21.000</span><span>€ 14.000</span><span>€ 7.000</span><span>€ 0</span></div><svg viewBox="0 0 760 250" preserveAspectRatio="none" aria-label="Evolución"><defs><linearGradient id="crFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#0FA7A0" stopOpacity=".35"/><stop offset="100%" stopColor="#0FA7A0" stopOpacity="0"/></linearGradient></defs><path d={chart.area} fill="url(#crFill)"/><path d={chart.line} fill="none" stroke="#20C9BF" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg><div className="chart-x-labels"><span>Ene</span><span>Feb</span><span>Mar</span><span>Abr</span><span>May</span><span>Jun</span><span>Jul</span><span>Ago</span><span>Sep</span><span>Oct</span><span>Nov</span><span>Dic</span></div></div><div className="chart-footer"><div><span>Valor total actual</span><strong>{eur(total)}</strong></div><div><span>Máximo histórico</span><strong>{eur(chart.max)}</strong></div><div><span>Mínimo histórico</span><strong>{eur(chart.min)}</strong></div></div></section>
 <section className="panel-card exchange-holdings-card"><div className="panel-head"><div><h3>Tus activos por exchange</h3><p>Valor consolidado según el último snapshot disponible.</p></div><Link className="panel-link" href="/dashboard/exchanges">Gestionar exchanges</Link></div>{exchangeRows.length?<div className="exchange-table"><div className="exchange-table-head"><span>Exchange</span><span>Valor total</span><span>% del total</span><span>Activos</span><span>Tendencia</span></div>{exchangeRows.map(ex=><div className="exchange-table-row" key={ex.code+ex.name}><div className="exchange-name"><span className="exchange-logo">{ex.code.slice(0,1)}</span><div><strong>{ex.name}</strong><small>{ex.assets} posiciones</small></div></div><strong>{eur(ex.value)}</strong><span>{total?((ex.value/total)*100).toFixed(1):"0.0"}%</span><span>{ex.assets}</span><span className="mini-trend">⌁⌁⌁⌁</span></div>)}</div>:<div className="empty-state"><strong>Aún no hay saldos para mostrar</strong><p>Conecta un exchange o importa un histórico para ver aquí tus activos.</p></div>}</section></div>
 <aside className="dashboard-right-column"><section className="pro-summary-card"><div className="pro-summary-icon">♛</div><div className="pro-summary-heading"><strong>Tu plan actual</strong><span>{plan}</span></div><ul><li>Soporte prioritario</li><li>Sin límites de importaciones</li><li>Informes fiscales avanzados</li><li>Acceso a todos los exchanges</li></ul>{!hasPro&&<Link className="btn btn-primary btn-full" href="/dashboard/configuracion">Mejorar a Pro</Link>}{hasPro&&<Link className="btn btn-outline-full" href="/dashboard/configuracion">Gestionar suscripción</Link>}</section><section className="panel-card quick-card"><div className="panel-head"><h3>Accesos rápidos</h3></div><div className="quick-grid"><Link href="/dashboard/importar">⇧<span>Importar CSV</span></Link><Link href="/dashboard/exchanges">↻<span>Conectar Exchange</span></Link><Link href="/dashboard/informes">▣<span>Ver informes</span></Link><Link href="/dashboard/ayuda">?<span>Ayuda</span></Link></div></section><section className="panel-card recent-card"><div className="panel-head"><h3>Movimientos recientes</h3><Link className="panel-link" href="/dashboard/movimientos">Ver todos</Link></div>{transactions?.length?<div className="recent-list">{transactions.map(tx=><div className="recent-row" key={tx.id}><span className="recent-icon">◆</span><div><strong>{tx.transaction_type}</strong><small>{(tx.accounts as {name?:string}|null)?.name||"Cuenta"} · {(tx.assets as {symbol?:string}|null)?.symbol||"Activo"}</small></div><div className="recent-value"><strong>{tx.quote_amount?`${Number(tx.quote_amount).toLocaleString("es-ES",{maximumFractionDigits:2})} ${tx.price_currency||""}`:"—"}</strong><small>{new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"short"}).format(new Date(tx.occurred_at))}</small></div></div>)}</div>:<div className="empty-state"><strong>Sin movimientos todavía</strong><p>Cuando haya actividad aparecerá aquí.</p></div>}</section></aside></div><div className="dashboard-footer-trust"><span>◈ <strong>Seguro y confiable</strong><small>Tus datos y claves siempre protegidos</small></span><span>▣ <strong>Cumplimiento fiscal</strong><small>Calcula y organiza tus impuestos</small></span><span>⟳ <strong>Conecta tus exchanges</strong><small>Automatiza la importación de datos</small></span><span>◉ <strong>Soporte en español</strong><small>Estamos aquí para ayudarte</small></span></div></section></main></div>
}
function Stat({icon,label,value,note}:{icon:string;label:string;value:string;note:string}){return <article className="stat-card stat-card-modern"><span className="modern-stat-icon">{icon}</span><span className="stat-label">{label}</span><strong>{value}</strong><span className="stat-note">{note}</span></article>}
function eur(value:number){return value.toLocaleString("es-ES",{style:"currency",currency:"EUR",maximumFractionDigits:2})}
function makeChart(rows:any[]){const map=new Map<string,number>();for(const row of rows){const d=new Date(row.captured_at).toISOString().slice(0,10);map.set(d,(map.get(d)||0)+Number(row.value_eur||0))}const values=[...map.values()];const source=values.length?values:[0];const max=Math.max(...source,1),min=Math.min(...source);const sampled=source.length>48?source.filter((_,i)=>i%Math.ceil(source.length/48)===0).slice(0,48):source;const points=sampled.map((v,i)=>`${(sampled.length===1?0:(i/(sampled.length-1))*760).toFixed(1)},${(220-(v/max)*195).toFixed(1)}`);return{line:`M ${points.join(" L ")}`,area:`M 0 220 L ${points.join(" L ")} L 760 220 Z`,max,min}}
