import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

export default async function ReportsPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/login");
 const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle(); const hasPro=profile?.role!=="free";
 return <div className="app-shell"><aside className="app-sidebar"><Link className="app-logo" href="/dashboard"><span className="brand-mark">₿</span><span className="brand-name">Coin<span>Renta</span></span></Link><nav className="app-nav"><Link className="app-nav-item" href="/dashboard">▦ Resumen</Link><Link className="app-nav-item active" href="/dashboard/informes">▣ Informes</Link><Link className="app-nav-item" href="/dashboard/ayuda">? Ayuda</Link></nav></aside><main className="app-main"><header className="app-topbar"><div><span className="topbar-kicker">CoinRenta Pro</span><h1>Informes</h1><p>Analiza tu patrimonio y prepara tu información fiscal.</p></div></header><section className="dashboard-content"><div className="stat-grid"><article className="stat-card"><span className="stat-label">Patrimonio</span><strong>EUR</strong><span className="stat-note">Evolución por periodo</span></article><article className="stat-card"><span className="stat-label">Distribución</span><strong>Exchanges</strong><span className="stat-note">Concentración de activos</span></article><article className="stat-card"><span className="stat-label">Fiscalidad</span><strong>FIFO</strong><span className="stat-note">Preparación de resultados</span></article></div>{hasPro?<div className="dashboard-grid"><section className="panel-card"><div className="panel-head"><div><span className="section-kicker">Informe patrimonial</span><h3>Evolución y distribución</h3></div></div><div className="empty-state"><strong>El motor de informes se conectará a tus snapshots</strong><p>Esta vista ya está preparada para mostrar gráficas históricas, distribución por activo/exchange y exportaciones.</p></div></section><section className="panel-card"><div className="panel-head"><div><span className="section-kicker">Fiscal</span><h3>Informe fiscal</h3></div></div><div className="empty-state"><strong>Informe fiscal avanzado</strong><p>Disponible para cuentas Pro y Admin cuando finalice el motor de cálculo fiscal.</p></div></section></div>:<div className="panel-card pro-lock"><span className="pro-summary-icon">♛</span><span className="section-kicker">Función Pro</span><h2>Desbloquea los informes avanzados</h2><p>Gráficas históricas, distribución de cartera, informes fiscales y exportaciones estarán disponibles con Pro.</p><Link className="btn btn-primary" href="/dashboard/configuracion">Pasar a Pro</Link></div>}</section></main></div>;
}
